mcmset de { \
"<New Database>" "<Neue Datenbank>" \
"<unknown>" "<unbekannt>" \
"About" "Über" \
"About ..." "Über ..." \
"About Password Gorilla" "Über Password Gorilla" \
"Add Group ..." "Gruppe hinzufügen ..." \
"Add Login" "Neuer Login" \
"Add Subgroup" "Neue Untergruppe" \
"Add Subgroup ..." "Untergruppe hinzufügen ..." \
"Add a new Group" "Neue Gruppe hinzufügen" \
"Add logins using \"Add Login\" in the \"Login\" menu." "Neue Logins können im <Login>-Menü angelegt werden." \
"Add/Edit/View Login" "Login hinzufügen/bearbeiten/ansehen" \
"Addition of group canceled." "Keine Gruppe hinzugefügt." \
"Also copy username to clipboard" "Auch den Benutzernamen in die Ablage kopieren." \
"Any field" "Alle Felder" \
"Are you sure that you want to delete group and all its contents?" "Soll die Gruppe wirklich mit dem gesamten Inhalt gelöscht werden?" \
"Are you sure that you want to delete this login?" "Soll der Login wirklich gelöscht werden?" \
"Auto-save database immediately when changed" "Datenbank sofort nach einer Änderung automatisch speichern" \
"Automatically copy password associated\nwith login to clipboard after pasting\nof user-name." "Kopiere automatisch das Passwort in die
Zwischenablage nach dem Einfügen des Benutzernamens." \
"Backup database on save" "Beim Speichern eine Sicherungskopie anlegen" \
"Browser" "Webbrowser" \
"Browser executable to launch (required):" "Browser-Programm (erforderlich):" \
"Browser launching is not configured. See help." "Der Browser ist nicht definiert. Mehr in der Hilfe." \
"Browser parameter lacks '%url%' string. See help." "In den Browser Parametern fehlt der '%url%' Platzhalter." \
"Can not copy $what to clipboard: no $what defined." "Kann $what nicht in die Ablage kopieren: $what ist nicht definiert." \
"Cancel" "Abbrechen" \
"Case sensitive find" "Groß/Kleinschreibung beachten" \
"Change Master Password ..." "Master Passwort ändern ..." \
"Clear" "Löschen" \
"Clear Clipboard" "Zwischenablage löschen" \
"Clear clipboard after" "Zwischenablage löschen nach" \
"Clipboard autoclear multiplier" "Löschfaktor für die Zwischenablage" \
"Clipboard cleared." "Zwischenablage geleert." \
"Close" "Schließen" \
"Command line parameter (if any) to pass (optional):" "(Eventuelle) Parameter für die Kommandozeile (optional):" \
"Confirm:" "Bestätigung:" \
"Contributors" "Mitarbeiter" \
"Copied $what to clipboard." "$what in die Ablage kopiert." \
"Copy Password" "Passwort kopieren" \
"Copy Password to Clipboard" "Kopiere Passwort in die Zwischenablage" \
"Copy URL" "URL kopieren" \
"Copy URL to Clipboard" "Kopiere URL in die Zwischenablage" \
"Copy Username" "Benutzernamen kopieren" \
"Copy Username to Clipboard" "Kopiere Benutzernamen in die Zwischenablage" \
"Copy password to clipboard" "Password in die Zwischenablage kopieren" \
"Current Master Password:" "Altes Master Passwort:" \
"Customize ..." "Anpassen ..." \
"Database Locked" "Datenbank gesperrt" \
"Database Preferences" "Datenbank Einstellungen" \
"Database exported." "Datenbank exportiert." \
"Database:" "Datenbank:" \
"Defaults" "Voreinstellungen" \
"Delete Group" "Gruppe löschen" \
"Delete Login" "Login löschen" \
"Destination Group with format <Group.Subgroup> :" "Zielgruppe im Format <Gruppe.Untergruppe> :" \
"Determines how Password\nGorilla handles clearing the\nclipboard.\n\nRange zero to twenty.\n\nSee Help for details." "Bestimmt, wie Password Gorilla die Zwischenablage löscht (0-20).
Mehr in der Hilfe." \
"Display" "Ansicht" \
"Do nothing" "Nichts tun" \
"Edit" "Bearbeiten" \
"Edit Login" "Login bearbeiten" \
"Enter the Master Password." "Bitte Master Passwort eingeben." \
"Error" "Fehler" \
"Error launching browser, the OS error message is:" "Kann Browser nicht starten, das Betriebssystem meldet:" \
"Exit" "Beenden" \
"Export" "Exportieren" \
"Export ..." "Exportieren ..." \
"Export Security Warning" "Sicherheitshinweis Export" \
"Export password database as text ..." "Exportiere die Datenbank unverschlüsselt ..." \
"Exporting ..." "Exportiere ..." \
"Field separator" "Feldbegrenzer" \
"File" "Datenbank" \
"Find" "Suche" \
"Find ..." "Suchen ..." \
"Find Browser" "Browser suchen" \
"Find Options ..." "Suchoptionen" \
"Find Text:" "Suchtext:" \
"Find next" "Nächstes" \
"General" "Allgemein" \
"Generate Password" "Passwort erzeugen" \
"Generate gorilladoc.html" "Gorilladoc.html erzeugen" \
"Group deleted." "Gruppe gelöscht." \
"Group name unchanged." "Gruppenname unverändert." \
"Group renamed." "Gruppe umbenannt." \
"Help" "Hilfe" \
"Help ..." "Hilfe ..." \
"Hide Password" "Passwort verbergen" \
"History deleted. After a restart the list will be empty." "Verlauf gelöscht. Nach einem Neustart ist die Liste leer." \
"Iconify upon auto-lock" "Beim Sperren minimieren" \
"If a command line parameter is provided, it must contain the character sequence: %url%. This sequence will be replaced with the actual URL during launch. See the help system for details." "Wenn Parameter in der Aufrufzeile angegeben werden, muss der Platzhalter %url% angegeben werden. Er übergibt die URL des Login-Eintrags an den Browser. Mehr in der Hilfe." \
"Include \"Notes\" field" "Notiz-Feld exportieren" \
"Include password field" "Passwort-Feld exportieren" \
"Language:" "Sprache:" \
"Launch Browser directed to URL" "Starte den Browser direkt mit der URL" \
"Launched browser:" "Gestarteter Browser:" \
"License" "Lizenz" \
"License ..." "Lizenz ..." \
"Lock now" "Sofort sperren" \
"Lock when idle after" "Sperren bei Untätigkeit nach" \
"Login" "Datensatz" \
"Login deleted." "Login gelöscht." \
"Login modified." "Login bearbeitet." \
"Master password changed." "Master Passwort geändert." \
"Merge ..." "Vereinigen ..." \
"Merge Password Database" "Importiere Passwort-Datenbank" \
"Merging" "Vereinigen" \
"Move $type" "Verschiebe $type" \
"Move Group ..." "Gruppe verschieben ..." \
"Move Login ..." "Login verschieben ..." \
"Moving of $type canceled." "Verschieben von $type abgebrochen." \
"New" "Neu" \
"New ..." "Neue ..." \
"New Database: Choose Master Password" "Neue Datenbank: Hauptpasswort wählen" \
"New Group Name:" "Name der neuen Gruppe:" \
"New Master Password:" "Neues Master Passwort:" \
"New group added." "Neue Gruppe hinzugefügt." \
"New login added." "Neuer Login angelegt." \
"Note: these defaults will be applied to new databases. To change a setting for an existing database, go to \"Customize\" in the \"Security\" menu." "Die Voreinstellungen werden auf neue Datenbanken angewendet.  Um die Einstellungen einer existierenden Datenbank zu ändern,  wählen Sie \"Anpassen ...\" im Menü \"Sicherheit\"." \
"Notes" "Notizen" \
"Notes:" "Notizen" \
"Oh well..." "Na gut ..." \
"Open ..." "Öffnen ..." \
"Open Password Database" "Passwort-Datenbank öffnen" \
"Open URL" "Springe zu URL" \
"Override Password Policy" "Passwort-Richtlinien
nicht beachten" \
"Parent:" "Elterngruppe:" \
"Password" "Passwort" \
"Password Gorilla - <New Database>" "Passwort Gorilla - <Neue Datenbank>" \
"Password Gorilla License" "Password Gorilla Lizenz" \
"Password Length" "Passwortlänge" \
"Password Policy ..." "Passwort Richtlinien" \
"Password database $nativeName loaded." " Passwort-Datenbank geladen." \
"Password database saved as $nativeName" "Die Passwort-Datenbank wurde als $nativeName gespeichert" \
"Password database saved." "Passwort-Datenbank gespeichert." \
"Password policy changed." "Passwortrichtlinien geändert." \
"Password policy settings invalid." "Passwort-Richtlinien fehlerhaft." \
"Password:" "Passwort:" \
"Passwords Do Not Match" "Die Passwörter stimmen nicht überein." \
"Please be patient. Verifying password ..." "Bitte etwas Geduld. Überprüfe Passwort ..." \
"Please change the file permissions to read-write and hit 'Retry' or hit 'Cancel' and use 'File'->'Save As' to save into a different file." "Entfernen Sie den Schreibschutz und wählen dann 'Wiederholen' oder brechen Sie den Vorgang ab und speichern Sie die Datei unter einem neuen Namen." \
"Preferences" "Einstellungen" \
"Preferences ..." "Einstellungen ..." \
"Remember" "Merke" \
"Remember sizes of dialog boxes" "Die Größe der Dialogboxen merken" \
"Rename Group" "Gruppe umbenennen" \
"Rename Group ..." "Gruppe umbenennen" \
"Save As ..." "Speichern als ..." \
"Save as Unicode text file" "Als Unicode-Textfeld speichern" \
"Save changes?" "Änderungen speichern?" \
"Security" "Sicherheit" \
"Select a database, and enter its password. Click \"New\" to create a new database." "Bitte Datenbank wählen und Passwort eingeben. Neue Datenbank mit Klick auf \"Neu\"" \
"Show Gorilla Icon" "Zeige den Gorilla" \
"Show Password" "Passwort zeigen" \
"Show security warning" "Zeige Sicherheitswarnung" \
"Size" "Größe" \
"Text not found." "Text nicht gefunden." \
"The confirmed password does not match." "Die Bestätigung des Passworts ist gescheitert." \
"The current password database is modified. Do you want to save the current database before creating the new database?" "Die aktuelle Datenbank wurde modifiziert. Soll sie vor dem Anlegen einer neuen Datenbank gespeichert werden?" \
"The current password database is modified. Do you want to save the database? <Yes> saves the database and exits. <No> discards all changes and exits. <Cancel> returns to the main menu." "Die Datenbank wurde modizifiert. Soll sie gespeichert werden?" \
"The selected login does not contain a URL value." "Der ausgewählte Datensatz enthält keinen URL-Eintrag." \
"This login must have a title." "Dieser Datensatz benötigt einen Titel-Eintrag." \
"This login's group name is not valid." "Der Gruppenname für diesen Datensatz ist ungültig." \
"This option does not function on\nWindows(TM) or MacOS(TM) platforms.\nSee the help system for details." "Diese Option ist auf Windows(TM) oder MacOS(TM) Plattformen ungültig." \
"Title" "Titel" \
"Use Gorilla auto-copy" "Gorillas auto-copy verwenden" \
"Use Password Safe 3 format" "Passwort Safe 3 Format verwenden" \
"Use UPPERCASE letters" "Großbuchstaben verwenden" \
"Use digits" "Ziffern verwenden" \
"Use easy to read characters only (e.g. no \"0\" or \"O\")" "Leicht zu lesende Buchstaben verwenden (z.B. kein \"0\" oder \"O\")" \
"Use hexadecimal digits" "Hexadezimale Ziffern verwenden" \
"Use lowercase letters" "Kleinbuchstaben verwenden" \
"Use symbols (%, \$, @, #, etc.)" "Sonderzeichen verwenden (%, $, @, #, etc.)" \
"Username" "Benutzername" \
"Using Password Gorilla" "Mit Password Gorilla arbeiten" \
"V2 Unicode support" "V2 Unicode Unterstützung" \
"V3 key stretching iterations" "Wiederholungen für das V3 <key stretching>" \
"View Login" "Login zeigen" \
"Warning: Can not save to" "Die Datei" \
"Warning: Read-only password file" "Warnung: Schreibgeschützte Datei" \
"Welcome back." "Sperre aufgehoben." \
"Welcome to the Password Gorilla." "Hallo bei Password Gorilla" \
"When double clicking a login ..." "Beim Doppelklick auf ein Login" \
"When selected the username\nfrom the login entry will also\nbe copied to the clipboard\nwhen opening a browser." "Auch der Benutzername wird nach dem Aufruf
des Browsers in die Zwischenablage gelegt." \
"You are about to export the password database to a plain-text file. The file will not be encrypted or password-protected. Anybody with access can read the file, and learn your user names and passwords. Make sure to store the file in a secure location. Do you want to continue?" "Die Datenbank wird unverschlüsselt und ohne Passwortschutz zugänglich sein. Sorgen Sie für eine sichere Aufbewahrung Ihrer Daten. Wollen Sie fortfahren?" \
"because the file permissions are set for read-only access." "kann nicht gesichert werden, weil sie schreibgeschützt ist." \
"database names" "Datenbanknamen" \
"minutes (0=never)" "Minuten (0=niemals)" \
"seconds (0=never)" "Sekunden (0=nie)" \
}
