mcmset de {
"File" "Datenbank" \
"New ..." "Neue ..."\
"Open ..." "Öffnen ..." \
"Merge ..." "Vereinigen ..."\
"Save" "Speichern"\
"Add" "neu" \
"Save As ..." "Speichern als ..." \
"Export ..." "Exportieren ..." \
"Preferences ..." "Einstellungen ..." \
"Preferences" "Einstellungen" \
"Edit" "Bearbeiten" \
"Copy Username" "Benutzernamen kopieren" \
"Copy Password" "Passwort kopieren" \
"Copy URL" "URL kopieren" \
"Clear Clipboard" "Zwischenablage löschen" \
"Find ..." "Suchen ..." \
"Find next" "Nächstes" \
"Manage" "Verwalten" \
"Help ..." "Hilfe ..." \
"Contributors" "Mitarbeiter" \
"Help" "Hilfe" \
"License ..." "Lizenz ..." \
"License" "Lizenz" \
"About" "Über" \
"Open Password Database" "Passwort-Datenbank öffnen" \
"Select a database, and enter its password." "Wähle eine Datenbank und gib das Passwort ein" \
"Create new password database" "Neue Passwort-Datenbank anlegen" \
"Open password database" "Passwort-Datenbank öffnen" \
"Merge a second database into this database" "Importiere eine zweite Datenbank" \
"Add a new Group" "Neue Gruppe hinzufügen" \
"Add Subgroup ..." "Untergruppe hinzufügen ..." \
"Add Group ..." "Gruppe hinzufügen" \
"Delete Group" "Gruppe löschen" \
"Rename Group ..." "Gruppe umbenennen" \
"Parent Group" "Übergeordnete Gruppe" \
"Group Name" "Gruppename" \
"Notes:" "Notizen" \
"Show Password" "Passwort zeigen" \
"Hide Password" "Passwort verbergen" \
"Password Policy ..." "Passwort Richtlinien" \
"Database Preferences" "Datenbank Einstellungen" \
"Database Preferences ..." "Datenbank Einstellungen ..." \
"Generate Password" "Passwort erzeugen" \
"Change Master Password ..." "Master Passwort ändern ..." \
"Override Password Policy" "Passwort-Richtlinien\nnicht beachten" \
"Password Length" "Passwortlänge" \
"Use lowercase letters" "Kleinbuchstaben verwenden" \
"Use UPPERCASE letters" "Großbuchstaben verwenden" \
"Use digits" "Ziffern verwenden" \
"Use hexadecimal digits" "Hexadezimale Ziffern verwenden" \
"Use symbols (%, \$, @, #, etc.)" "Sonderzeichen verwenden (%, \$, @, #, etc.)" \
"Use easy to read characters only (e.g. no \"0\" or \"O\")" "Leicht zu lesende Buchstaben verwenden (z.B. kein \"0\" oder \"O\")" \
"Lock when idle after" "Sperren bei Untätigkeit von" \
"minutes (0=never)" "Minuten (0=niemals)" \
"Auto-save database immediately when changed" "Datenbank sofort nach einer Änderung\n automatisch speichern" \
"Use Password Safe 3 format" "Passwort Safe 3 Format verwenden" \
"V2 Unicode support" "V2 Unicode Unterstützung" \
"Delete Group" "Gruppe löschen" \
"Rename Group ..." "Gruppe umbenennen" \
"Parent Group" "Übergeordnete Gruppe" \
"Group Name" "Gruppename" \
"Notes:" "Notizen" \
"Show Password" "Passwort zeigen" \
"Hide Password" "Passwort verbergen" \
"Generate Password" "Passwort erzeugen" \
"Override\nPassword Policy" "Passwort-Richtlinien\nnicht beachten" \
"Password Length" "Passwortlänge" \
"Use lowercase letters" "Kleinbuchstaben verwenden" \
"Use UPPERCASE letters" "Großbuchstaben verwenden" \
"Use digits" "Ziffern verwenden" \
"Use hexadecimal digits" "Hexadezimale Ziffern verwenden" \
"Use symbols (%, \$, @, #, etc.)" "Sonderzeichen verwenden (%, \$, @, #, etc.)" \
"Use easy to read characters only (e.g. no \"0\" or \"O\")" "Leicht zu lesende Buchstaben verwenden (z.B. kein \"0\" oder \"O\")" \
"Lock when idle after" "Sperren bei Untätigkeit nach" \
"minutes (0=never)" "Minuten (0=niemals)" \
"Auto-save database immediately when changed" "Datenbank sofort nach einer Änderung automatisch speichern" \
"Use Password Safe 3 format" "Passwort Safe 3 Format verwenden" \
"V2 Unicode support" "V2 Unicode Unterstützung" \
"V3 key stretching iterations" "Wiederholungen für das V3 <key stretching>" \
"General" "Allgemein" \
"Clear clipboard after" "Zwischenablage löschen nach" \
"seconds (0=never)" "Sekunden (0=nie)" \
"Remember" "Merke" \
"database names" "Datenbanknamen" \
"Clear" "Löschen" \
"When double clicking a login ..." "Beim Doppelklick auf ein Login" \
"Copy password to clipboard" "Password in die Zwischenablage kopieren" \
"(Not available with v2 database format.)" "Im v2 Datenbank-Format nicht verfügbar" \
"Add Login ..." "Login hinzufügen ..." \
"Language" "Sprache" \
"Cancel" "Abbrechen" \
"Create new password database" "Neue Passwort Datenbank" \
"Edit Login ..." "Login bearbeiten ..." \
"Edit Login" "Login bearbeiten" \
"Delete Login" "Login löschen" \
"Do nothing" "Nichts tun" \
"Backup database on save" "Beim Speichern eine Sicherungskopie anlegen" \
"Remember sizes of dialog boxes" "Die Größe der Dialogboxen merken" \
"Defaults" "Voreinstellungen" \
"Note: these defaults will be applied to\
new databases. To change a setting for an existing\
database, go to \"Customize\" in the \"Security\"\
menu." "Die Voreinstellungen werden auf neue Datenbanken angewendet. \
Um die Einstellungen einer existierenden Datenbank zu ändern, \
wählen Sie \"Anpassen ...\" im Menü \"Sicherheit\"." \
"Include password field" "Passwort-Feld exportieren" \
"Include \"Notes\" field" "Notiz-Feld exportieren" \
"Save as Unicode text file" "Als Unicode-Textfeld speichern" \
"Field separator" "Feldbegrenzer" \
"Show security warning" "Zeige Sicherheitswarnung" \
"Close" "Schließen" \
"<New Database>" "<Neue Datenbank>" \
"Database:" "Datenbank:" \
"Browse" "Suchen" \
"Password:" "Passwort:" \
"Please be patient. Verifying password ..." "Bitte etwas Geduld. Überprüfe Passwort ..." \
"Exit" "Beenden" \
"The Database Is Locked" "Die Datenbank ist gesperrt" \
"Enter the Master Password." "Bitte Master Passwort eingeben." \
"Find" "Suche" \
"Find in ..." "Suche in ..." \
"Any field" "Beliebiges Feld" \
"Title" "Titel" \
"Username" "Benutzername" \
"Case sensitive find" "Suche abhängig von der Groß- und Kleinschreibung" \
"Add Login ..." "Login hinzufügen ..." \
"Welcome to the Password Gorilla." "Hallo bei Password Gorilla" \
"Add/Edit/View Login" "Login hinzufügen/bearbeiten/ansehen" \
"Password database saved as $nativeName" "Die Passwort-Datenbank wurde als $nativeName gespeichert" \
"Password database saved." "Passwort-Datenbank gespeichert." \
"Current Master Password:" "Altes Master Passwort:" \
"New Master Password:" "Neues Master Passwort:" \
"Confirm:" "Bestätigung:" \
"The current password database is modified.\
	Do you want to save the database?\n\
	\"Yes\" saves the database, and exits.\n\
	\"No\" discards all changes, and exits.\n\
	\"Cancel\" returns to the main menu." "Die Datenbank wurde modifiziert. Sollen die Änderungen gespeichert werden?" \
"Login unchanged." "Login wurde nicht verändert" \
"Copy Username to Clipboard" "Kopiere Benutzernamen in die Zwischenablage" \
"Copy Password to Clipboard" "Kopiere Passwort in die Zwischenablage" \
"Copy URL to Clipboard" "Kopiere URL in die Zwischenablage" \
"Add Login" "Neuer Login" \
"Add Subgroup" "Neue Untergruppe" \
"Rename Group" "Gruppe umbenennen" \
"Copied password to clipboard." "Passwort in die Zwischenablage kopiert." \
"Using Password Gorilla" "Mit Password Gorilla arbeiten" \
"Database exported." "Datenbank exportiert." \
"Exporting ..." "Exportiere ..." \
"Export password database as text ..." "Exportiere die Datenbank unverschlüsselt ..." \
"Export Security Warning" "Sicherheitshinweis Export" \
"You are about to export the password\
		database to a plain-text file. The file will\
		not be encrypted or password-protected. Anybody\
		with access can read the file, and learn your\
		user names and passwords. Make sure to store the\
		file in a secure location. Do you want to\
		continue?" "Die Datenbank wird unverschlüsselt und ohne\
		Passwortschutz zugänglich sein. Sorgen Sie für eine 
		sichere Aufbewahrung Ihrer Daten. Wollen Sie fortfahren?" \
"Copied user name to clipboard." "Benutzernamen in die Zwischenablage kopiert." \
"Copied URL to clipboard." "URL in die Zwischenablage kopiert." \
"Can not copy URL to clipboard: no URL defined." "Fehler: Keine URL definiert." \
"Clipboard cleared." "Zwischenablage geleert." \
"Any field" "Alle Felder" \
"Find Options ..." "Suchoptionen" \
"Case sensitive find" "Groß/Kleinschreibung beachten" \
"Login deleted." "Login gelöscht." \
"Are you sure that you want to delete this login?" "Soll der Login wirklich gelöscht werden?" \
"Move Login ..." "Login verschieben ..." \
"Move Group ..." "Gruppe verschieben ..." \
"Move" "Verschiebe ..." \
"Group" "Gruppe" \
"Destination Group with format <Group.Subgroup> :" "Zielgruppe im Format <Gruppe.Untergruppe> :" \
"Database Locked" "Datenbank gesperrt" \
"Merge Password Database" "Importiere Passwort-Datenbank" \
"Add logins using \"Add Login\" in the \"Login\" menu." "Jetzt können Logins angelegt werden." \
"Password database $nativeName loaded." " Passwort-Datenbank geladen." \
"Addition of new login canceled." "Ein neuer Login wurde nicht angelegt." \
"New login added." "Neuer Login angelegt." \
"Login modified." "Login bearbeitet." \
"Group deleted." "Gruppe gelöscht." \
"Group name unchanged." "Gruppenname unverändert." \
"Group renamed." "Gruppe umbenannt." \
"Merging" "Vereinige mit" \
"Welcome back." "Sperre aufgehoben." \
"Password policy changed." "Passwortrichtlinien geändert." \
"Text not found." "Text nicht gefunden." \
"Parent:" "Elterngruppe:" \
"Are you sure that you want to delete group and all its contents?" "Soll die Gruppe wirklich mit dem gesamten Inhalt gelöscht werden?" \
"New Group Name:" "Name der neuen Gruppe:" \
"Notes" "Notizen" \
"Find Text:" "Suchtext:" \
"New" "Neu" \
"Select a database, and enter its password. Click \"New\" to create a new database." "Bitte Datenbank wählen und Passwort eingeben. Neue Datenbank mit Klick auf \"Neu\"" \
"New Database: Choose Master Password" "Neue Datenbank: Hauptpasswort wählen" \
"Browse for a password database ..." "Passwort Datenbank suchen ..." \
"Display" "Ansicht" \
"Language:" "Sprache:" \
"Security" "Sicherheit" \
"Customize ..." "Anpassen ..." \
"Lock now" "Sofort sperren" \
"View Login" "Login zeigen" \
"Password" "Passwort" \
"Last Password Change" "Letzte Passwortänderung" \
"Last Modified" "Zuletzt geändert" \
"Notes" "Notizen" \
"Size" "Größe" \
"Show Gorilla Icon" "Zeige den Gorilla" \
"Iconify upon auto-lock" "Beim Sperren minimieren" \
"Warning: Can not save to" "Die Datei" \
"because the file permissions are set for read-only access." "kann nicht gesichert werden, weil sie schreibgeschützt ist." \
"Please change the file permissions to read-write and hit 'Retry' or hit 'Cancel' and use 'File'->'Save As' to save into a different file." "Entfernen Sie den Schreibschutz und wählen dann 'Wiederholen' oder brechen Sie den Vorgang ab und speichern Sie die Datei unter einem neuen Namen." \
"Warning: Read-only password file" "Warnung: Schreibgeschützte Datei" \
"<unknown>" "unbekannt" \
"About Password Gorilla" "Über Password Gorilla" \
"Addition of group canceled." "Keine Gruppe hinzugefügt." \
"Also copy username to clipboard" "Auch den Benutzernamen in die Ablage kopieren." \
"Browser" "Webbrowser" \
"Browser executable to launch (required):" "Browser-Programm (erforderlich):" \
"Can not copy $what to clipboard: no $what defined." "Kann $what nicht in die Ablage kopieren: $what ist nicht definiert." \
"Command line parameter (if any) to pass (optional):" "(Eventuelle) Parameter für die Kommandozeile (optional):" \
"Copied $what to clipboard." "$what in die Ablage kopiert." \
"Error" "Fehler" \
"Error launching browser, the OS error message is:" "Kann Browser nicht starten, das Betriebssystem meldet:" \
"Export" "Exportieren" \
"Find Browser" "Browser suchen" \
"History deleted. After a restart the list will be empty." "Verlauf gelöscht. Nach einem Neustart ist die Liste leer." \
"Launch Browser directed to URL" "Starte den Browser direkt mit der URL" \
"Launched browser:" "Gestarteter Browser:" \
"Master password changed." "Master Passwort geändert." \
"Move $type" "Verschiebe $type" \
"Moving of $type canceled." "Verschieben von $type abgebrochen." \
"New group added." "Neue Gruppe hinzugefügt." \
"Oh well..." "Na gut ..." \
"Open URL" "Springe zu URL" \
"Password Gorilla - <New Database>" "Passwort Gorilla - <Neue Datenbank>" \
"Password Gorilla License" "Password Gorilla Lizenz" \
"Password policy settings invalid." "Passwort-Richtlinien fehlerhaft." \
"Passwords Do Not Match" "Die Passwörter stimmen nicht überein." \
"Save changes?" "Änderungen speichern?" \
"The confirmed password does not match." "Die Bestätigung des Passworts ist gescheitert." \
"The selected login does not contain a URL value." "Der ausgewählte Datensatz enthält keinen URL-Eintrag." \
"This login must have a title." "Dieser Datensatz benötigt einen Titel-Eintrag." \
"This login's group name is not valid." "Der Gruppenname für diesen Datensatz ist ungültig." \
"Use Gorilla auto-copy" "Gorillas auto-copy verwenden" \
"Generate gorilladoc.html" "Gorilladoc.html erzeugen" \
"Automatically copy password associated\nwith login to clipboard after pasting\nof user-name." "Kopiere das Login-Passwort automatisch in die Zwischenablage nach dem Einfügen des Benutzernamens." \
"Browser launching is not configured.  See help." "Der Browser ist noch nicht definiert." \
"Browser parameter lacks '%url%' string.  See help." "Browser Parameter ohne '%url%' String." \
"Determines how Password\nGorilla handles clearing the\nclipboard.\n\nRange zero to twenty.\n\nSee Help for details." "Definiert das Löschintervall der Zwischenablage (0-20).\nMehr in der Hilfe." \
"If a command line parameter is provided, it must contain the character sequence: %url%.  This sequence will be replaced with the actual URL during launch.  See the help system for details." "In der Kommandozeile muss der Platzhalter %url% erscheinen, der dem Browser als URL-Adresse übergeben wird. Mehr in der Hilfe." \
"The current password database is modified.\
		Do you want to save the current database before creating\
		the new database?" "Die aktuelle Datenbank wurde modifiziert. Soll sie vor dem Anlegen einer neuen Datenbank gespeichert werden?" \
"This option does not function on\nWindows(TM) or MacOS(TM) platforms.\nSee the help system for details." "Diese Option kann auf Windows(TM) \noder MacOS(TM) Systemen nicht eingesetzt werden." \
"When selected the username\nfrom the login entry will also\nbe copied to the clipboard\nwhen opening a browser." "Kopiere den Benutzernamen in die Zwischenablage beim Öffnen des Browsers." \
"Clipboard autoclear multiplier" "Löschfaktor der Zwischenablage" \
}

