mcmset de {
"<New Database>" "<New Database>" \
"<unknown>" "<unknown>" \
"About" "About" \
"About Password Gorilla" "About Password Gorilla" \
"Add Login" "Add Login" \
"Add Subgroup" "Add Subgroup" \
"Add a new Group" "Add a new Group" \
"Add logins using \"Add Login\" in the \"Login\" menu." "Add logins using \"Add Login\" in the \"Login\" menu." \
"Add/Edit/View Login" "Add/Edit/View Login" \
"Addition of group canceled." "Addition of group canceled." \
"Also copy username to clipboard" "Also copy username to clipboard" \
"Any field" "Any field" \
"Are you sure that you want to delete group and all its contents?" "Are you sure that you want to delete group and all its contents?" \
"Are you sure that you want to delete this login?" "Are you sure that you want to delete this login?" \
"Auto-save database immediately when changed" "Auto-save database immediately when changed" \
"Automatically copy password associated\nwith login to clipboard after pasting\nof user-name." "Automatically copy password associated\nwith login to clipboard after pasting\nof user-name." \
"Backup database on save" "Backup database on save" \
"Browser" "Browser" \
"Browser executable to launch (required):" "Browser executable to launch (required):" \
"Browser launching is not configured.  See help." "Browser launching is not configured.  See help." \
"Browser parameter lacks '%url%' string.  See help." "Browser parameter lacks '%url%' string.  See help." \
"Can not copy $what to clipboard: no $what defined." "Can not copy $what to clipboard: no $what defined." \
"Cancel" "Cancel" \
"Case sensitive find" "Case sensitive find" \
"Clear" "Clear" \
"Clear clipboard after" "Clear clipboard after" \
"Clipboard cleared." "Clipboard cleared." \
"Close" "Close" \
"Command line parameter (if any) to pass (optional):" "Command line parameter (if any) to pass (optional):" \
"Confirm:" "Confirm:" \
"Contributors" "Contributors" \
"Copied $what to clipboard." "Copied $what to clipboard." \
"Copy Password to Clipboard" "Copy Password to Clipboard" \
"Copy URL to Clipboard" "Copy URL to Clipboard" \
"Copy Username to Clipboard" "Copy Username to Clipboard" \
"Copy password to clipboard" "Copy password to clipboard" \
"Current Master Password:" "Current Master Password:" \
"Database Locked" "Database Locked" \
"Database Preferences" "Database Preferences" \
"Database exported." "Database exported." \
"Database:" "Database:" \
"Defaults" "Defaults" \
"Delete Group" "Delete Group" \
"Delete Login" "Delete Login" \
"Destination Group with format <Group.Subgroup> :" "Destination Group with format <Group.Subgroup> :" \
"Determines how Password\nGorilla handles clearing the\nclipboard.\n\nRange zero to twenty.\n\nSee Help for details." "Determines how Password\nGorilla handles clearing the\nclipboard.\n\nRange zero to twenty.\n\nSee Help for details." \
"Display" "Display" \
"Do nothing" "Do nothing" \
"Edit Login" "Edit Login" \
"Enter the Master Password." "Enter the Master Password." \
"Error" "Error" \
"Error launching browser, the OS error message is:" "Error launching browser, the OS error message is:" \
"Exit" "Exit" \
"Export" "Export" \
"Export Security Warning" "Export Security Warning" \
"Export password database as text ..." "Export password database as text ..." \
"Exporting ..." "Exporting ..." \
"Field separator" "Field separator" \
"Find" "Find" \
"Find Browser" "Find Browser" \
"Find Options ..." "Find Options ..." \
"Find Text:" "Find Text:" \
"General" "General" \
"Generate Password" "Generate Password" \
"Generate gorilladoc.html" "Generate gorilladoc.html" \
"Group deleted." "Group deleted." \
"Group name unchanged." "Group name unchanged." \
"Group renamed." "Group renamed." \
"Hide Password" "Hide Password" \
"History deleted. After a restart the list will be empty." "History deleted. After a restart the list will be empty." \
"Iconify upon auto-lock" "Iconify upon auto-lock" \
"If a command line parameter is provided, it must contain the character sequence: %url%.  This sequence will be replaced with the actual URL during launch.  See the help system for details." "If a command line parameter is provided, it must contain the character sequence: %url%.  This sequence will be replaced with the actual URL during launch.  See the help system for details." \
"Include \"Notes\" field" "Include \"Notes\" field" \
"Include password field" "Include password field" \
"Language:" "Language:" \
"Launch Browser directed to URL" "Launch Browser directed to URL" \
"Launched browser:" "Launched browser:" \
"License" "License" \
"Lock when idle after" "Lock when idle after" \
"Login deleted." "Login deleted." \
"Login modified." "Login modified." \
"Master password changed." "Master password changed." \
"Merge Password Database" "Merge Password Database" \
"Merging " "Merging " \
"Move $type" "Move $type" \
"Moving of $type canceled." "Moving of $type canceled." \
"New" "New" \
"New Database: Choose Master Password" "New Database: Choose Master Password" \
"New Group Name:" "New Group Name:" \
"New Master Password:" "New Master Password:" \
"New group added." "New group added." \
"New login added." "New login added." \
"Note: these defaults will be applied to\
	new databases. To change a setting for an existing\
	database, go to \"Customize\" in the \"Security\"\
	menu." "Note: these defaults will be applied to\
	new databases. To change a setting for an existing\
	database, go to \"Customize\" in the \"Security\"\
	menu." \
"Notes" "Notes" \
"Notes:" "Notes:" \
"Oh well..." "Oh well..." \
"Open Password Database" "Open Password Database" \
"Open URL" "Open URL" \
"Override Password Policy" "Override Password Policy" \
"Parent:" "Parent:" \
"Password" "Password" \
"Password Gorilla - <New Database>" "Password Gorilla - <New Database>" \
"Password Gorilla License" "Password Gorilla License" \
"Password Length" "Password Length" \
"Password database $nativeName loaded." "Password database $nativeName loaded." \
"Password database saved as $nativeName" "Password database saved as $nativeName" \
"Password database saved." "Password database saved." \
"Password policy changed." "Password policy changed." \
"Password policy settings invalid." "Password policy settings invalid." \
"Password:" "Password:" \
"Passwords Do Not Match" "Passwords Do Not Match" \
"Please be patient. Verifying password ..." "Please be patient. Verifying password ..." \
"Please change the file permissions to read-write and hit 'Retry' or hit 'Cancel' and use 'File'->'Save As' to save into a different file." "Please change the file permissions to read-write and hit 'Retry' or hit 'Cancel' and use 'File'->'Save As' to save into a different file." \
"Preferences" "Preferences" \
"Remember" "Remember" \
"Remember sizes of dialog boxes" "Remember sizes of dialog boxes" \
"Rename Group" "Rename Group" \
"Save as Unicode text file" "Save as Unicode text file" \
"Save changes?" "Save changes?" \
"Select a database, and enter its password. Click \"New\" to create a new database." "Select a database, and enter its password. Click \"New\" to create a new database." \
"Show Gorilla Icon" "Show Gorilla Icon" \
"Show Password" "Show Password" \
"Show security warning" "Show security warning" \
"Size" "Size" \
"Text not found." "Text not found." \
"The confirmed password does not match." "The confirmed password does not match." \
"The current password database is modified.\
		Do you want to save the current database before creating\
		the new database?" "The current password database is modified.\
		Do you want to save the current database before creating\
		the new database?" \
"The current password database is modified.\
		Do you want to save the database?\n\
		\"Yes\" saves the database, and exits.\n\
		\"No\" discards all changes, and exits.\n\
		\"Cancel\" returns to the main menu." "The current password database is modified.\
		Do you want to save the database?\n\
		\"Yes\" saves the database, and exits.\n\
		\"No\" discards all changes, and exits.\n\
		\"Cancel\" returns to the main menu." \
"The selected login does not contain a URL value." "The selected login does not contain a URL value." \
"This login must have a title." "This login must have a title." \
"This login's group name is not valid." "This login's group name is not valid." \
"This option does not function on\nWindows(TM) or MacOS(TM) platforms.\nSee the help system for details." "This option does not function on\nWindows(TM) or MacOS(TM) platforms.\nSee the help system for details." \
"Title" "Title" \
"Use Gorilla auto-copy" "Use Gorilla auto-copy" \
"Use Password Safe 3 format" "Use Password Safe 3 format" \
"Use UPPERCASE letters" "Use UPPERCASE letters" \
"Use digits" "Use digits" \
"Use easy to read characters only (e.g. no \"0\" or \"O\")" "Use easy to read characters only (e.g. no \"0\" or \"O\")" \
"Use hexadecimal digits" "Use hexadecimal digits" \
"Use lowercase letters" "Use lowercase letters" \
"Use symbols (%, \$, @, #, etc.)" "Use symbols (%, \$, @, #, etc.)" \
"Username" "Username" \
"Using Password Gorilla" "Using Password Gorilla" \
"V2 Unicode support" "V2 Unicode support" \
"V3 key stretching iterations" "V3 key stretching iterations" \
"View Login" "View Login" \
"Warning: Can not save to" "Warning: Can not save to" \
"Warning: Read-only password file" "Warning: Read-only password file" \
"Welcome back." "Welcome back." \
"Welcome to the Password Gorilla." "Welcome to the Password Gorilla." \
"When double clicking a login ..." "When double clicking a login ..." \
"When selected the username\nfrom the login entry will also\nbe copied to the clipboard\nwhen opening a browser." "When selected the username\nfrom the login entry will also\nbe copied to the clipboard\nwhen opening a browser." \
"You are about to export the password\
					database to a plain-text file. The file will\
					not be encrypted or password-protected. Anybody\
					with access can read the file, and learn your\
					user names and passwords. Make sure to store the\
					file in a secure location. Do you want to\
					continue?" "You are about to export the password\
					database to a plain-text file. The file will\
					not be encrypted or password-protected. Anybody\
					with access can read the file, and learn your\
					user names and passwords. Make sure to store the\
					file in a secure location. Do you want to\
					continue?" \
"because the file permissions are set for read-only access." "because the file permissions are set for read-only access." \
"database names" "database names" \
"minutes (0=never)" "minutes (0=never)" \
"seconds (0=never)" "seconds (0=never)" \
}
