# Project-Id-Version: PACKAGE VERSION
# Report-Msgid-Bugs-To: 
# POT-Creation-Date: 2011-07-17 21:42-0400
# PO-Revision-Date: 2011-06-15 09:10+0100
# Last-Translator: zdia <z.dia@gmx.de>
# Language-Team: LANGUAGE <LL@li.org>
# MIME-Version: 1.0
# Content-Type: text/plain; charset=UTF-8
# Content-Transfer-Encoding: 8bit

mcmset en {
File File
{New ...} {New ...}
{Open ...} {Open ...}
{Merge ...} {Merge ...}
Save Save
{Save As ...} {Save As ...}
{Export ...} {Export ...}
{Import ...} {Import ...}
{Preferences ...} {Preferences ...}
Exit Exit
Edit Edit
{Copy Username} {Copy Username}
{Copy Password} {Copy Password}
{Copy URL} {Copy URL}
{Clear Clipboard} {Clear Clipboard}
{Find ...} {Find ...}
{Find next} {Find next}
Login Login
{Add Login} {Add Login}
{Edit Login} {Edit Login}
{View Login} {View Login}
{Delete Login} {Delete Login}
{Move Login ...} {Move Login ...}
{Add Group ...} {Add Group ...}
{Add Subgroup ...} {Add Subgroup ...}
{Rename Group ...} {Rename Group ...}
{Move Group ...} {Move Group ...}
{Delete Group} {Delete Group}
Security Security
{Password Policy ...} {Password Policy ...}
{Customize ...} {Customize ...}
{Change Master Password ...} {Change Master Password ...}
{Lock now} {Lock now}
Help Help
{Help ...} {Help ...}
{License ...} {License ...}
{About ...} {About ...}
{Need %s} {Need %s}
{The Password Gorilla requires the "%s" package. This seems to be an installation problem, as this file ought to be part of the Password Gorilla distribution.

Error message: %s} {The Password Gorilla requires the "%s" package. This seems to be an installation problem, as this file ought to be part of the Password Gorilla distribution.

Error message: %s}
{Need [Incr Tcl]} {Need [Incr Tcl]}
{The Password Gorilla requires the [incr Tcl] add-on to Tcl. Please install the [incr Tcl] package.

Error Message: %s} {The Password Gorilla requires the [incr Tcl] add-on to Tcl. Please install the [incr Tcl] package.

Error Message: %s}
{Need PWSafe} {Need PWSafe}
{The Password Gorilla requires the "pwsafe" package. This seems to be an installation problem, as the pwsafe package ought to be part of the Password Gorilla distribution.

Error Message: %s} {The Password Gorilla requires the "pwsafe" package. This seems to be an installation problem, as the pwsafe package ought to be part of the Password Gorilla distribution.

Error Message: %s}
{Welcome to the Password Gorilla.} {Welcome to the Password Gorilla.}
About About
{Add Subgroup} {Add Subgroup}
{Rename Group} {Rename Group}
{Open URL} {Open URL}
{Copy Username to Clipboard} {Copy Username to Clipboard}
{Copy Password to Clipboard} {Copy Password to Clipboard}
{Copy URL to Clipboard} {Copy URL to Clipboard}
{Move Login to:} {Move Login to:}
{Save changes?} {Save changes?}
{The current password database is modified. Do you want to save the current database before creating the new database?} {The current password database is modified. Do you want to save the current database before creating the new database?}
{New Database: Choose Master Password} {New Database: Choose Master Password}
{Password Gorilla - <New Database>} {Password Gorilla - <New Database>}
{<New Database>} {<New Database>}
{Add logins using <Add Login> in the <Login> menu.} {Add logins using <Add Login> in the <Login> menu.}
{Opening ... %2.0f %%} {Opening ... %2.0f %%}
Database: Database:
Password: Password:
OK OK
New New
{Select a database, and enter its password. Click "New" to create a new database.} {Select a database, and enter its password. Click "New" to create a new database.}
{Please be patient. Verifying password ...} {Please be patient. Verifying password ...}
{Error Opening Database} {Error Opening Database}
{Can not open password database "%s": %s} {Can not open password database "%s": %s}
{Browse for a password database ...} {Browse for a password database ...}
{Open Password Database} {Open Password Database}
{Password database %s loaded.} {Password database %s loaded.}
{Add/Edit/View Login} {Add/Edit/View Login}
Cancel Cancel
{Show Password} {Show Password}
{Generate Password} {Generate Password}
{Override Password Policy} {Override Password Policy}
{Password Length} {Password Length}
{Hide Password} {Hide Password}
{Password policy settings invalid.} {Password policy settings invalid.}
<unknown> <unknown>
{This login must have a title, url or username.} {This login must have a title, url or username.}
{This login's group name is not valid.} {This login's group name is not valid.}
{New login added.} {New login added.}
{Login modified.} {Login modified.}
{Group entries may be renamed, not edited.} {Group entries may be renamed, not edited.}
{Destination Group with format <Group.Subgroup> :} {Destination Group with format <Group.Subgroup> :}
{Invalid Group Name} {Invalid Group Name}
{The group name can not be empty.} {The group name can not be empty.}
{The name of the parent group is invalid.} {The name of the parent group is invalid.}
{Are you sure that you want to delete this login?} {Are you sure that you want to delete this login?}
{Login deleted.} {Login deleted.}
{Add a new Group} {Add a new Group}
Parent: Parent:
{New Group Name:} {New Group Name:}
{Addition of group canceled.} {Addition of group canceled.}
{New group added.} {New group added.}
{Root Node Can Not Be Moved} {Root Node Can Not Be Moved}
{The root node can not be moved.} {The root node can not be moved.}
{Can Not Move Node} {Can Not Move Node}
{Can not move a group to a subgroup of itself.} {Can not move a group to a subgroup of itself.}
{Are you sure that you want to delete group and all its contents?} {Are you sure that you want to delete group and all its contents?}
{Group deleted.} {Group deleted.}
{Group name unchanged.} {Group name unchanged.}
{Group renamed.} {Group renamed.}
{Export Security Warning} {Export Security Warning}
{You are about to export the password database to a plain-text file. The file will not be encrypted or password-protected. Anybody with access can read the file, and learn your user names and passwords. Make sure to store the file in a secure location. Do you want to continue?} {You are about to export the password database to a plain-text file. The file will not be encrypted or password-protected. Anybody with access can read the file, and learn your user names and passwords. Make sure to store the file in a secure location. Do you want to continue?}
{Export password database as text ...} {Export password database as text ...}
{Error Exporting Database} {Error Exporting Database}
{Failed to export password database to} {Failed to export password database to}
{Exporting ...} {Exporting ...}
{Database exported.} {Database exported.}
{Import CSV datafile} {Import CSV datafile}
{Error opening import CSV file} {Error opening import CSV file}
{Could not access file } {Could not access file }
{Error parsing CSV file} {Error parsing CSV file}
{Error parsing first line of CSV file, unable to continue.} {Error parsing first line of CSV file, unable to continue.}
{Error, nothing to import.} {Error, nothing to import.}
{No valid import data was found.  Please see
the help for details on how to format import
CSV data files for Password Gorilla.} {No valid import data was found.  Please see
the help for details on how to format import
CSV data files for Password Gorilla.}
{Error, undefined data columns} {Error, undefined data columns}
{The following data items are not recognized as import data items.
Unable to continue.} {The following data items are not recognized as import data items.
Unable to continue.}
{Some records from the CSV file were not imported.
Do you wish to save a log of skipped records?} {Some records from the CSV file were not imported.
Do you wish to save a log of skipped records?}
{Some records skipped during import} {Some records skipped during import}
{Enter a file into which to save the log} {Enter a file into which to save the log}
{record(s) successfully imported.} {record(s) successfully imported.}
{Saving ... %2.0f %%} {Saving ... %2.0f %%}
{Merge Password Database} {Merge Password Database}
Merging Merging
Close Close
{Warning: Can not save to} {Warning: Can not save to}
{because the file permissions are set for read-only access.} {because the file permissions are set for read-only access.}
{Please change the file permissions to read-write and hit 'Retry' or hit 'Cancel' and use 'File'->'Save As' to save into a different file.} {Please change the file permissions to read-write and hit 'Retry' or hit 'Cancel' and use 'File'->'Save As' to save into a different file.}
{Warning: Read-only password file} {Warning: Read-only password file}
{Error Saving Backup of Database} {Error Saving Backup of Database}
{Failed to save password database as
%s: %s} {Failed to save password database as
%s: %s}
{Password database saved with backup copy %s.} {Password database saved with backup copy %s.}
{Password database saved.} {Password database saved.}
{Nothing To Save} {Nothing To Save}
{No password database to save.} {No password database to save.}
{Save password database ...} {Save password database ...}
{Error Saving Database} {Error Saving Database}
{Failed to save password database as "%s": %s} {Failed to save password database as "%s": %s}
{Password database saved with backup copy} {Password database saved with backup copy}
ERROR-SaveBackup {Error Saving Backup of Database}
ERROR-SaveBackup-no-directory {No directory selected. - 
Please define a backup directory
in the Preferences menu.}
ERROR-SaveBackup-invalid-directory {No valid directory. - 
Please define a valid backup directory
in the Preferences menu.}
ERROR-SaveBackup-unknown-file {Unknown file. - 
Please select a valid database filename.}
ERROR-SaveBackup-failed {Failed to make backup copy of password
database as %s: 
%s}
{The current password database is modified. Do you want to save the database? <Yes> saves the database and exits. <No> discards all changes and exits. <Cancel> returns to the main menu.} {The current password database is modified. Do you want to save the database? <Yes> saves the database and exits. <No> discards all changes and exits. <Cancel> returns to the main menu.}
{Clipboard cleared.} {Clipboard cleared.}
{Database Locked} {Database Locked}
{Enter the Master Password.} {Enter the Master Password.}
{error: %s} {error: %s}
{Wrong Password} {Wrong Password}
{That password is not correct.} {That password is not correct.}
{Welcome back.} {Welcome back.}
Confirm: Confirm:
{Passwords Do Not Match} {Passwords Do Not Match}
{The confirmed password does not match.} {The confirmed password does not match.}
{Password policy changed.} {Password policy changed.}
{Use lowercase letters} {Use lowercase letters}
{Use UPPERCASE letters} {Use UPPERCASE letters}
{Use digits} {Use digits}
{Use hexadecimal digits} {Use hexadecimal digits}
{Use symbols (%, $, @, #, etc.)} {Use symbols (%, $, @, #, etc.)}
{Use easy to read characters only (e.g. no "0" or "O")} {Use easy to read characters only (e.g. no "0" or "O")}
{Lock when idle after} {Lock when idle after}
{minutes (0=never)} {minutes (0=never)}
{Auto-save database immediately when changed} {Auto-save database immediately when changed}
{Use Password Safe 3 format} {Use Password Safe 3 format}
{V2 Unicode support} {V2 Unicode support}
{V3 key stretching iterations} {V3 key stretching iterations}
SECURITY-db-calc-delay-time {Calculate delay time}
SECURITY-db-%d-iter-%s-secs {%d iterations produces 
%s seconds of delay}
SECURITY-db-calc Calculate
SECURITY-db-calcing Working
SECURITY-db-auto-iter-calc {Automatic iteration calculation}
SECURITY-db-delay-for {Delay for}
SECURITY-db-seconds seconds
Preferences Preferences
General General
{When double clicking a login ...} {When double clicking a login ...}
{Copy password to clipboard} {Copy password to clipboard}
{Launch Browser directed to URL} {Launch Browser directed to URL}
{Do nothing} {Do nothing}
{Clear clipboard after} {Clear clipboard after}
{seconds (0=never)} {seconds (0=never)}
Remember Remember
{database names} {database names}
Clear Clear
{Backup database on save} {Backup database on save}
{Remember sizes of dialog boxes} {Remember sizes of dialog boxes}
{Use Gorilla auto-copy} {Use Gorilla auto-copy}
{Automatically copy password associated
with login to clipboard after pasting
of user-name.} {Automatically copy password associated
with login to clipboard after pasting
of user-name.}
{This option does not function on
Windows(TM) or MacOS(TM) platforms.
See the help system for details.} {This option does not function on
Windows(TM) or MacOS(TM) platforms.
See the help system for details.}
Defaults Defaults
{Time stamp backup} {Time stamp backup}
{Backup path:} {Backup path:}
{Choose a directory} {Choose a directory}
{Note: these defaults will be applied to new databases. To change a setting for an existing database, go to "Customize" in the "Security" menu.} {Note: these defaults will be applied to new databases. To change a setting for an existing database, go to "Customize" in the "Security" menu.}
Export Export
{Include password field} {Include password field}
{Include "Notes" field} {Include "Notes" field}
{Field separator} {Field separator}
{Show security warning} {Show security warning}
Display Display
Language: Language:
Size Size
{Show Gorilla Icon} {Show Gorilla Icon}
{Iconify upon auto-lock} {Iconify upon auto-lock}
{Hide login name in tree view} {Hide login name in tree view}
{This option takes effect after exiting
and restarting of Password Gorilla} {This option takes effect after exiting
and restarting of Password Gorilla}
Browser Browser
{Browser executable to launch (required):} {Browser executable to launch (required):}
{Command line parameter (if any) to pass (optional):} {Command line parameter (if any) to pass (optional):}
{Find Browser} {Find Browser}
{If a command line parameter is provided, it must contain the character sequence: %url%. This sequence will be replaced with the actual URL during launch. See the help system for details.} {If a command line parameter is provided, it must contain the character sequence: %url%. This sequence will be replaced with the actual URL during launch. See the help system for details.}
{Also copy username to clipboard} {Also copy username to clipboard}
{When selected the username
from the login entry will also
be copied to the clipboard
when opening a browser.} {When selected the username
from the login entry will also
be copied to the clipboard
when opening a browser.}
{Determines how Password
Gorilla handles clearing the
clipboard.

Range zero to twenty.

See Help for details.} {Determines how Password
Gorilla handles clearing the
clipboard.

Range zero to twenty.

See Help for details.}
{Clipboard autoclear multiplier} {Clipboard autoclear multiplier}
{History deleted. After a restart the list will be empty.} {History deleted. After a restart the list will be empty.}
Error Error
{Error while saving RC-File} {Error while saving RC-File}
{No Database} {No Database}
{Please create a new database, or open an existing
database first.} {Please create a new database, or open an existing
database first.}
{Current Master Password:} {Current Master Password:}
{New Master Password:} {New Master Password:}
{Password Not Changed} {Password Not Changed}
{You canceled the setting of a new password.
Therefore, the existing password remains in effect.} {You canceled the setting of a new password.
Therefore, the existing password remains in effect.}
{Master password changed.} {Master password changed.}
{Can not copy %s to clipboard: no %s defined.} {Can not copy %s to clipboard: no %s defined.}
{Copied %s to clipboard.} {Copied %s to clipboard.}
{Password Gorilla} {Password Gorilla}
{Gorilla will protect your passwords and help you to manage them with a pwsafe 3.2 compatible database} {Gorilla will protect your passwords and help you to manage them with a pwsafe 3.2 compatible database}
Contributors Contributors
{Gorilla artwork contributed by %s} {Gorilla artwork contributed by %s}
{German translation by %s} {German translation by %s}
{Russian translation by %s} {Russian translation by %s}
{Italian translation by %s} {Italian translation by %s}
License License
{About Password Gorilla} {About Password Gorilla}
{Password Gorilla License} {Password Gorilla License}
{Find Text:} {Find Text:}
{Find Options ...} {Find Options ...}
{Any field} {Any field}
Title Title
Username Username
Password Password
Notes Notes
URL URL
{Case sensitive find} {Case sensitive find}
Find Find
{Text not found.} {Text not found.}
{Please select a login entry first.} {Please select a login entry first.}
{The selected login does not contain a URL value.} {The selected login does not contain a URL value.}
{Browser launching is not configured. See help.} {Browser launching is not configured. See help.}
{Browser parameter lacks '%url%' string. See help.} {Browser parameter lacks '%url%' string. See help.}
{Error launching browser, the OS error message is:} {Error launching browser, the OS error message is:}
{Oh well...} {Oh well...}
{Launched browser:} {Launched browser:}
{Generate gorilladoc.html} {Generate gorilladoc.html}
}
