mcmset fr {
	"File" "Fichier" \
	"New ..." "Nouveau ..."\
	"Open ..." "Ouvrire ..." \
	"Merge ..." "Importieren ..."\
	"Save" "Speichern"\
	"Add" "neu" \
	"Save As ..." "Speichern als ..." \
	"Export ..." "Exportieren ..." \
	"Preferences ..." "Einstellungen ..." \
	"Preferences" "Einstellungen" \
	"Edit" "Bearbeiten" \
	"Copy Username" "Benutzernamen kopieren" \
	"Copy Password" "Passwort kopieren" \
	"Copy URL" "URL kopieren" \
	"Clear Clipboard" "Zwischenablage löschen" \
	"Find ..." "Suchen ..." \
	"Find next" "Nächstes" \
	"Manage" "Verwalten" \
	"Help ..." "Hilfe ..." \
	"Help" "Hilfe" \
	"License ..." "Lizenz ..." \
	"License" "Lizenz" \
	"Contributors" "Mitarbeiter" \
	"About ..." "Über ..." \
	"Open Password Database" "Passwort-Datenbank öffnen" \
	"Select a database, and enter its password." "Wähle eine Datenbank und gib das Passwort ein" \
	"Create new password database" "Neue Passwort-Datenbank anlegen" \
	"Open password database" "Passwort-Datenbank öffnen" \
	"Merge a second database into this database" "Importiere eine zweite Datenbank" \
	"Add a new Group" "Neue Gruppe hinzufügen" \
	"Add Subgroup ..." "Untergruppe hinzufügen ..." \
	"Add Group ..." "Gruppe hinzufügen" \
	"Delete Group" "Gruppe löschen" \
	"Rename Group ..." "Gruppe umbenennen" \
	"Parent Group" "Übergeordnete Gruppe" \
	"Group Name" "Gruppename" \
	"Notes:" "Notizen" \
	"Show Password" "Passwort zeigen" \
	"Hide Password" "Passwort verbergen" \
	"Password Policy ..." "Passwort Richtlinien" \
	"Database Preferences" "Datenbank Einstellungen" \
	"Database Preferences ..." "Datenbank Einstellungen ..." \
	"Generate Password" "Passwort erzeugen" \
	"Change Master Password ..." "Master Passwort ändern ..." \
	"Override Password Policy" "Passwort-Richtlinien\nnicht beachten" \
	"Password Length" "Passwortlänge" \
	"Use lowercase letters" "Kleinbuchstaben verwenden" \
	"Use UPPERCASE letters" "Großbuchstaben verwenden" \
	"Use digits" "Ziffern verwenden" \
	"Use hexadecimal digits" "Hexadezimale Ziffern verwenden" \
	"Use symbols (%, \$, @, #, etc.)" "Sonderzeichen verwenden (%, \$, @, #, etc.)" \
	"Use easy to read characters only (e.g. no \"0\" or \"O\")" "Leicht zu lesende Buchstaben verwenden (z.B. kein \"0\" oder \"O\")" \
	"Lock when idle after" "Sperren bei Untätigkeit von" \
	"minutes (0=never)" "Minuten (0=niemals)" \
	"Auto-save database immediately when changed" "Datenbank sofort nach einer Änderung\n automatisch speichern" \
	"Use Password Safe 3 format" "Passwort Safe 3 Format verwenden" \
	"V2 Unicode support" "V2 Unicode Unterstützung" \
	"Delete Group" "Gruppe löschen" \
	"Rename Group ..." "Gruppe umbenennen" \
	"Parent Group" "Übergeordnete Gruppe" \
	"Group Name" "Gruppename" \
	"Notes:" "Notizen" \
	"Show Password" "Passwort zeigen" \
	"Hide Password" "Passwort verbergen" \
	"Generate Password" "Passwort erzeugen" \
	"Override\nPassword Policy" "Passwort-Richtlinien\nnicht beachten" \
	"Password Length" "Passwortlänge" \
	"Use lowercase letters" "Kleinbuchstaben verwenden" \
	"Use UPPERCASE letters" "Großbuchstaben verwenden" \
	"Use digits" "Ziffern verwenden" \
	"Use hexadecimal digits" "Hexadezimale Ziffern verwenden" \
	"Use symbols (%, \$, @, #, etc.)" "Sonderzeichen verwenden (%, \$, @, #, etc.)" \
	"Use easy to read characters only (e.g. no \"0\" or \"O\")" "Leicht zu lesende Buchstaben verwenden (z.B. kein \"0\" oder \"O\")" \
	"Lock when idle after" "Sperren bei Untätigkeit nach" \
	"minutes (0=never)" "Minuten (0=niemals)" \
	"Auto-save database immediately when changed" "Datenbank sofort nach einer Änderung automatisch speichern" \
	"Use Password Safe 3 format" "Passwort Safe 3 Format verwenden" \
	"V2 Unicode support" "V2 Unicode Unterstützung" \
	"V3 key stretching iterations" "Wiederholungen für das V3 <key stretching>" \
	"General" "Allgemein" \
	"Clear clipboard after" "Zwischenablage löschen nach" \
	"seconds (0=never)" "Sekunden (0=nie)" \
	"Remember" "Merke" \
	"database names" "Datenbanknamen" \
	"Clear" "Löschen" \
	"When double clicking a login ..." "Beim Doppelklick auf ein Login" \
	"Copy password to clipboard" "Password in die Zwischenablage kopieren" \
	"(Not available with v2 database format.)" "Im v2 Datenbank-Format nicht verfügbar" \
	"Add Login ..." "Login hinzufügen ..." \
	"Language" "Sprache" \
	"Cancel" "Abbrechen" \
	"Create new password database" "Neue Passwort Datenbank" \
	"Edit Login ..." "Login bearbeiten ..." \
	"Edit Login" "Login bearbeiten" \
	"Delete Login" "Login löschen" \
	"Do nothing" "Nichts tun" \
	"Backup database on save" "Beim Speichern eine Sicherungskopie anlegen" \
	"Remember sizes of dialog boxes" "Die Größe der Dialogboxen merken" \
	"Defaults" "Voreinstellungen" \
	"Note: these defaults will be applied to\
		new databases. To change a setting for an existing\
		database, go to \"Database Preferences\" in the \"Manage\"\
		menu." "Die Voreinstellungen werden auf neue Datenbanken angewendet. Um die Einstellungen einer existierenden Datenbank zu ändern, wählen Sie \"Datenbank Einstellungen\" im \"Manage\" Menǘ" \
	"Include password field" "Passwort-Feld exportieren" \
	"Include \"Notes\" field" "Notiz-Feld exportieren" \
	"Save as Unicode text file" "Als Unicode-Textfeld speichern" \
	"Field separator" "Feldbegrenzer" \
	"Show security warning" "Zeige Sicherheitswarnung" \
	"Close" "Schließen" \
	"<New Database>" "<Neue Datenbank>" \
	"Database:" "Datenbank:" \
	"Browse" "Suchen" \
	"Password:" "Passwort:" \
	"Please be patient. Verifying password ..." "Bitte etwas Geduld. Überprüfe Passwort ..." \
	"Exit" "Quitter" \
	"The Database Is Locked" "Die Datenbank ist gesperrt" \
	"Enter the Master Password." "Bitte Master Passwort eingeben." \
	"Find" "Suche" \
	"Find in ..." "Suche in ..." \
	"Any field" "Beliebiges Feld" \
	"Title" "Titel" \
	"Username" "Benutzername" \
	"Case sensitive find" "Suche abhängig von der Groß- und Kleinschreibung" \
	"Add Login ..." "Login hinzufügen ..." \
	"Welcome to the Password Gorilla." "Hallo bei Password Gorilla" \
	"Add/Edit/View Login" "Login hinzufügen/bearbeiten/ansehen" \
	"Password database saved as $nativeName" "Die Passwort-Datenbank wurde als $nativeName gespeichert" \
	"Password database saved." "Passwort-Datenbank gespeichert." \
	"Current Master Password:" "Altes Master Passwort:" \
	"New Master Password:" "Neues Master Passwort:" \
	"Confirm:" "Bestätigung:" \
	"The current password database is modified.\
		Do you want to save the database?\n\
		\"Yes\" saves the database, and exits.\n\
		\"No\" discards all changes, and exits.\n\
		\"Cancel\" returns to the main menu." "Die Datenbank wurde modifiziert. Sollen die Änderungen gespeichert werden?" \
	"Login unchanged." "Login wurde nicht verändert" \
	"Copy Username to Clipboard" "Kopiere Benutzernamen in die Zwischenablage" \
	"Copy Password to Clipboard" "Kopiere Passwort in die Zwischenablage" \
	"Copy URL to Clipboard" "Kopiere URL in die Zwischenablage" \
	"Add Login" "Neuer Login" \
	"Add Subgroup" "Neue Untergruppe" \
	"Rename Group" "Gruppe umbenennen" \
	"Copied password to clipboard." "Passwort in die Zwischenablage kopiert." \
	"Using Password Gorilla" "Mit Password Gorilla arbeiten" \
	"Database exported." "Datenbank exportiert." \
	"Exporting ..." "Exportiere ..." \
	"Export password database as text ..." "Exportiere die Datenbank unverschlüsselt ..." \
	"Export Security Warning" "Sicherheitshinweis Export" \
	"You are about to export the password\
			database to a plain-text file. The file will\
			not be encrypted or password-protected. Anybody\
			with access can read the file, and learn your\
			user names and passwords. Make sure to store the\
			file in a secure location. Do you want to\
			continue?" "Die Datenbank wird unverschlüsselt und ohne\
			Passwortschutz zugänglich sein. Sorgen Sie für eine 
			sichere Aufbewahrung Ihrer Daten. Wollen Sie fortfahren?" \
	"Copied user name to clipboard." "Benutzernamen in die Zwischenablage kopiert." \
	"Copied URL to clipboard." "URL in die Zwischenablage kopiert." \
	"Can not copy URL to clipboard: no URL defined." "Fehler: Keine URL definiert." \
	"Clipboard cleared." "Zwischenablage geleert." \
	"Any field" "Alle Felder" \
	"Find Options ..." "Suchoptionen" \
	"Case sensitive find" "Groß/Kleinschreibung beachten" \
	"Login deleted." "Login gelöscht." \
	"Are you sure that you want to delete this login?" "Soll der Login wirklich gelöscht werden?" \
	"Move Login ..." "Login verschieben ..." \
	"Move Group ..." "Gruppe verschieben ..." \
	"Move" "Verschiebe ..." \
	"Group" "Gruppe" \
	"Destination Group with format <Group.Subgroup> :" "Zielgruppe im Format <Gruppe.Untergruppe> :" \
	"Database Locked" "Datenbank gesperrt" \
	"Merge Password Database" "Importiere Passwort-Datenbank" \
	"Add logins using <Add Login> in the \"Login\" menu." "Jetzt können Logins angelegt werden." \
	"Password database $nativeName loaded." " Passwort-Datenbank geladen." \
	"Addition of new login canceled." "Ein neuer Login wurde nicht angelegt." \
	"New login added." "Neuer Login angelegt." \
	"Login modified." "Login bearbeitet." \
	"Group deleted." "Gruppe gelöscht." \
	"Group name unchanged." "Gruppenname unverändert." \
	"Group renamed." "Gruppe umbenannt." \
	"Merging " "Vereinige mit " \
	"Welcome back." "Sperre aufgehoben." \
	"Password policy changed." "Passwortrichtlinien geändert." \
	"Text not found." "Text nicht gefunden." \
	"Parent:" "Elterngruppe:" \
	"Are you sure that you want to delete group and all its contents?" "Soll die Gruppe wirklich mit dem gesamten Inhalt gelöscht werden?" \
	"New Group Name:" "Name der neuen Gruppe:" \
	"Notes" "Notizen" \
	"Find Text:" "Suchtext:" \
	"New" "Neu" \
	"Select a database, and enter its password. Click \"New\" to create a new database." "Bitte Datenbank wählen und Passwort eingeben. Neue Datenbank mit Klick auf \"Neu\"" \
	"New Database: Choose Master Password" "Neue Datenbank: Hauptpasswort wählen" \
	}
	
mcunknown de "unbekannt"
