# Project-Id-Version: PACKAGE VERSION
# PO-Revision-Date: 2011-05-23 23:59+0200
# Last-Translator: Marco Ciampa <ciampix@libero.it>
# Language-Team: Italian <it@li.org>
# MIME-Version: 1.0
# Content-Type: text/plain; charset=UTF-8
# Content-Transfer-Encoding: 8bit

mcmset it {
File File
{New ...} {Nuovo ...}
{Open ...} {Apri ...}
{Merge ...} {Fondi ...}
Save Salva
{Save As ...} {Salva come ...}
{Export ...} {Esporta ...}
{Import ...} {Importa ...}
{Preferences ...} {Preferenze ...}
Exit Esci
Edit Modifica
{Copy Username} {Copia nome utente}
{Copy Password} {Copia password}
{Copy URL} {Copia URL}
{Clear Clipboard} {Cancella gli appunti}
{Find ...} {Trova ...}
{Find next} {Trova il prossimo}
Login Login
{Add Login} {Nuovo login}
{Edit Login} {Modifica login}
{View Login} {Mostra il login}
{Delete Login} {Cancella login}
{Move Login ...} {Sposta login ...}
{Add Group ...} {Nuovo gruppo ...}
{Add Subgroup ...} {Nuovo sottogruppo ...}
{Rename Group ...} {Rinomina gruppo ...}
{Move Group ...} {Sposta gruppo ...}
{Delete Group} {Cancella gruppo}
Security Sicurezza
{Password Policy ...} {Criteri password ...}
{Customize ...} {Personalizza ...}
{Change Master Password ...} {Cambia la password principale ...}
{Lock now} {Blocca ora}
Help Aiuto
{Help ...} {Aiuto ...}
{License ...} {Licenza ...}
{About ...} {Informazioni ...}
{Need %s} {Server %s}
{The Password Gorilla requires the "%s" package. This seems to be an installation problem, as this file ought to be part of the Password Gorilla distribution.

Error message: %s} {Password Gorilla necessita del pacchetto "%s". Sembrerebbe un problema di installazione dato che questo file fa parte della distribuzione di Password Gorilla.

Messaggio di errore: %s}
{Need [Incr Tcl]} {Server [Incr Tcl]}
{The Password Gorilla requires the [incr Tcl] add-on to Tcl. Please install the [incr Tcl] package.

Error Message: %s} {Password Gorilla necessita della funzionalità [incr Tcl] aggiunta a Tcl. Installare il pacchetto [incr Tcl].

Messaggio di errore: %s}
{Need PWSafe} {Server PWSafe}
{The Password Gorilla requires the "pwsafe" package. This seems to be an installation problem, as the pwsafe package ought to be part of the Password Gorilla distribution.

Error Message: %s} {Password Gorilla necessita del pacchetto "pwsafe". Sembrerebbe un problema di installazione dato che questo pacchetto fa parte della distribuzione di Password Gorilla.

Messaggio di errore: %s}
{Welcome to the Password Gorilla.} {Benvenuti in Password Gorilla}
About Informazioni
{Add Subgroup} {Nuovo sottogruppo}
{Rename Group} {Rinomina gruppo}
{Open URL} {Apri URL}
{Copy Username to Clipboard} {Copia nome utente negli appunti}
{Copy Password to Clipboard} {Copia password negli appunti}
{Copy URL to Clipboard} {Copia URL negli appunti}
{Move Login to:} {Sposta login a:}
{Save changes?} {Salvare i cambiamenti?}
{The current password database is modified. Do you want to save the current database before creating the new database?} {L'archivio corrente è stato modificato. Salvare l'archivio corrente prima di crearne uno nuovo?}
{New Database: Choose Master Password} {Nuovo archivio: scegliere la password principale}
{Password Gorilla - <New Database>} {Password Gorilla - <Nuovo archivio>}
{<New Database>} {<Nuovo archivio>}
{Add logins using <Add Login> in the <Login> menu.} {Aggiungi un nuovo login tramite il menu <Login>.}
{Opening ... %2.0f %%} {Apertura ... %2.0f %%}
Database: Archivio:
Password: Password:
OK OK
New Nuovo
{Select a database, and enter its password. Click "New" to create a new database.} {Selezionare un archivio e inserire la password. Clic su "Nuovo" per creare un nuovo archivio password.}
{Please be patient. Verifying password ...} {Verifica password. Attendere prego ...}
{Error Opening Database} {Errore durante l'apertura dell'archivio}
{Can not open password database "%s": %s} {Impossibile aprire l'archivio database "%s": %s}
{Browse for a password database ...} {Seleziona un archivio password ...}
{Open Password Database} {Apri archivio password}
{Password database %s loaded.} {Archivio password "%s" caricato.}
{Add/Edit/View Login} {Nuovo/modifica/mostra login}
Cancel Annulla
{Show Password} {Mostra password}
{Generate Password} {Genera password}
{Override Password Policy} {Passa sopra ai criteri delle password}
{Password Length} {Lunghezza password}
{Hide Password} {Nascondi la password}
{Password policy settings invalid.} {Impostazioni criteri password non valide.}
<unknown> <sconosciuto>
{This login must have a title, url or username.} {Questo login deve avere un titolo, un url o un nome utente.}
{This login's group name is not valid.} {Questo nome di gruppo di login non è valido.}
{New login added.} {Nuovo login aggiunto.}
{Login modified.} {Login modificato.}
{Group entries may be renamed, not edited.} {Le voci di gruppo possono essere rinominate, non modificate.}
{Destination Group with format <Group.Subgroup> :} {Gruppo di destinazione con formato <Gruppo.Sottogruppo> :}
{Invalid Group Name} {Nome gruppo non valido}
{The group name can not be empty.} {Il nome gruppo non può essere vuoto.}
{The name of the parent group is invalid.} {Il nome del gruppo genitore non è valido.}
{Are you sure that you want to delete this login?} {Sicuri di voler cancellare questo login?}
{Login deleted.} {Login cancellato.}
{Add a new Group} {Aggiungi un nuovo sottogruppo}
Parent: Genitore:
{New Group Name:} {Nome del nuovo gruppo:}
{Addition of group canceled.} {Nuovo login annullato.}
{New group added.} {Nuovo gruppo aggiunto.}
{Root Node Can Not Be Moved} {Il nodo radice non può essere spostato}
{The root node can not be moved.} {Il nodo radice non può essere spostato.}
{Can Not Move Node} {Impossibile spostare il nodo}
{Can not move a group to a subgroup of itself.} {Impossibile spostare un gruppo in un sottogruppo di sé stesso.}
{Are you sure that you want to delete group and all its contents?} {Sicuri di voler cancellare il gruppo e tutto il suo contenuto?}
{Group deleted.} {Gruppo cancellato.}
{Group name unchanged.} {Nome del gruppo non modificato.}
{Group renamed.} {Gruppo rinominato.}
{Export Security Warning} {Avvertimento di sicurezza all'esportazione}
{You are about to export the password database to a plain-text file. The file will not be encrypted or password-protected. Anybody with access can read the file, and learn your user names and passwords. Make sure to store the file in a secure location. Do you want to continue?} {Si sta per esportare l'archivio delle password su di un file di testo in chiaro. Il file non verrà criptato né protetto da password. Chiunque ne guadagni l'accesso potrà leggere il file, ed apprendere i nomi utenti e le password. Assicuratevi di salvare il file in un posto sicuro. Continuare?}
{Export password database as text ...} {Esporta l'archivio delle password come testo ...}
{Error Exporting Database} {Errore durante l'esportazione dell'archivio}
{Failed to export password database to} {Fallita l'esportazione dell'archivio password su}
{Exporting ...} {Esportazione ...}
{Database exported.} {Archivio esportato.}
{Import CSV datafile} {Importare un file dati CSV}
{Error opening import CSV file} {Errore all'apertura di un file di importazione CSV}
{Could not access file } {Impossibile accedere al file}
{Error parsing CSV file} {Errore nell'analisi del file CVS}
{Error parsing first line of CSV file, unable to continue.} {Errore durante l'analisi della prima riga del file CSV, impossibile continuare.}
{Error, nothing to import.} {Errore, niente da importare.}
{No valid import data was found.  Please see
the help for details on how to format import
CSV data files for Password Gorilla.} {Nessun dato importabile valido trovato. Consultare
la guida per i dettagli su come formattare i dati
CVS per l'importazione in Password Gorilla.}
{Error, undefined data columns} {Errore, colonne dati non definite}
{The following data items are not recognized as import data items.
Unable to continue.} {I seguenti elementi dati non sono stati riconosciuti come dati importabili.
Impossibile continuare.}
{Some records from the CSV file were not imported.Do you wish to save a log of skipped records?} {Alcuni record del file CVS non sono stati importati.Salvare il registro dei record saltati?}
{Some records skipped during import} {Alcuni record saltati durante l'importazione}
{Enter a file into which to save the log} {Inserire il file nel quale salvare il registo}
{record(s) successfully imported.} {record importati con successo.}
{Saving ... %2.0f %%} {Salvataggio ... %2.0f %%}
{Merge Password Database} {Fondi l'archivio password}
Merging Fusione
Close Chiudi
{Warning: Can not save to} {Attenzione: impossibile salvare su}
{because the file permissions are set for read-only access.} {dato che i permessi sul file sono impostati per la sola lettura.}
{Please change the file permissions to read-write and hit 'Retry' or hit 'Cancel' and use 'File'->'Save As' to save into a different file.} {Cambiare i permessi al file per consentire la lettura e scrittura e premere 'Riprova' o premere 'Annulla' e usare 'File'->'Salva come' per salvare in un file differente.}
{Warning: Read-only password file} {Attenzione: file delle password in sola lettura}
{Password database saved.} {Archivio password salvato.}
{Save password database ...} {Salvataggio archivio password ...}
{Error Saving Database} {Errore durante il salvataggio dell'archivio}
{Failed to make backup copy of password database as "%s": %s} {Fallito il salvataggio della copia di scorta dell'archivio password come "%s": %s}
{Failed to save password database as "%s": %s} {Fallito il salvataggio dell'archivio password come "%s": %s}
{Password database saved as %s} {Archivio password salvato come %s}
{The current password database is modified. Do you want to save the database? <Yes> saves the database and exits. <No> discards all changes and exits. <Cancel> returns to the main menu.} {L'archivio delle password corrente è stato modificato. Salvare l'archivio? <Sì> salva l'archivio e esce. <No> abbandona tutte le modifiche e esce. <Annulla> ritorna al menu principale.}
{Clipboard cleared.} {Appunti cancellati.}
{Database Locked} {Archivio bloccato}
{Enter the Master Password.} {Inserisci la password principale.}
{error: %s} {errore: %s}
{Wrong Password} {Password errata}
{That password is not correct.} {La password è sbagliata.}
{Welcome back.} Bentornati.
Confirm: Conferma:
{Passwords Do Not Match} {Le password non corrispondono.}
{The confirmed password does not match.} {La password di conferma non corrisponde.}
{Password policy changed.} {Criteri password modificati.}
{Use lowercase letters} {Usa le lettere minuscole}
{Use UPPERCASE letters} {Usa le lettere MAIUSCOLE}
{Use digits} {Usa le cifre}
{Use hexadecimal digits} {Usa le cifre esadecimali}
{Use symbols (%, $, @, #, etc.)} {Usa i simboli (%, $, @, #, ecc.)}
{Use easy to read characters only (e.g. no "0" or "O")} {Usa solo i caratteri semplici da leggere (perciò no "0" o "O")}
{Database Preferences} {Preferenze archivio}
{Lock when idle after} {Blocca dopo inattività per}
{minutes (0=never)} {minuti (0=mai)}
{Auto-save database immediately when changed} {Immediato auto salvataggio dell'archivio alla modifica}
{Use Password Safe 3 format} {Usa il formato password Safe 3}
{V2 Unicode support} {Supporto Unicode V2}
{V3 key stretching iterations} {Iterazioni V3 'key stretching'}
Preferences Preferenze
General Generale
{When double clicking a login ...} {Quando si fa doppio clic su un login ...}
{Copy password to clipboard} {Copia password negli appunti}
{Launch Browser directed to URL} {Esegui il browser indirizzato all'URL}
{Do nothing} {Non fare nulla}
{Clear clipboard after} {Cancella gli appunti dopo}
{seconds (0=never)} {secondi (0=mai)}
Remember Ricorda
{database names} {Nomi archivi}
Clear Cancella
{Backup database on save} {Copia di sicurezza dell'archivio al salvataggio}
{Remember sizes of dialog boxes} {Ricorda le dimensioni delle finestre di dialogo}
{Use Gorilla auto-copy} {Usa l'auto-copia di Gorilla}
{Automatically copy password associated
with login to clipboard after pasting
of user-name.} {Copia automatica della password associata
con il login negli appunti dopo aver incollato
il nome utente.}
{This option does not function on
Windows(TM) or MacOS(TM) platforms.
See the help system for details.} {Quest'opzione non funziona sulle
piattaforme Windows(TM) o MacOS(TM).
Consultare la guida per i dettagli.}
Defaults {Valori predefiniti}
{Note: these defaults will be applied to new databases. To change a setting for an existing database, go to "Customize" in the "Security" menu.} {Nota: queste impostazioni predefinite verranno applicate ai nuovi archivi. Per cambiare un'impostazione per un archivio esistente, selezionare "Personalizza" nel menu "Sicurezza".}
Export Esporta
{Include password field} {Includi il campo "Password"}
{Include "Notes" field} {Includi il campo "Notes"}
{Field separator} {Separatore di campo}
{Show security warning} {Mostra l'avviso di sicurezza}
Display Mostra
Language: Lingua:
Size Dimensione
{Show Gorilla Icon} {Mostra l'icona del Gorilla}
{Iconify upon auto-lock} {Riduci ad icona durante l'auto blocco}
{Hide login name in tree view} {Nascondi i nomi di login nella vista ad albero}
{This option takes effect after exiting
and restarting of Password Gorilla} {Questa opzione diventa attiva dopo l'uscita
e il riavvio di Password Gorilla.}
Browser Browser
{Browser executable to launch (required):} {Comando con cui eseguire il browser (richiesto):}
{Command line parameter (if any) to pass (optional):} {(Eventuale) Parametro da passare alla riga di comando (opzionale):}
{Find Browser} {Trova il browser}
{If a command line parameter is provided, it must contain the character sequence: %url%. This sequence will be replaced with the actual URL during launch. See the help system for details.} {Se viene fornito un parametro in riga di comando, questo deve contenere la sequenza di caratteri %url% . Questa sequenza verrà rimpiazzata dall'URL usato durante l'avvio del browser. Consultare la guida per i dettagli.}
{Also copy username to clipboard} {Inoltre, copia il nome utente negli appunti.}
{When selected the username
from the login entry will also
be copied to the clipboard
when opening a browser.} {Impostando il nome utente nella voce
di login, all'apertura del browser, esso
verrà copiato anche negli appunti.}
{Determines how Password
Gorilla handles clearing the
clipboard.

Range zero to twenty.

See Help for details.} {Determina come Password Gorilla
gestisce la cancellazione degli
appunti.

Da zero a venti.

Consultare la guida per i dettagli.}
{Clipboard autoclear multiplier} {Moltiplicatore autocancellazione appunti}
{History deleted. After a restart the list will be empty.} {Cronologia cancellata. Dopo il riavvio l'elenco sarà vuoto.}
{No Database} {Nessun archivio}
{Please create a new database, or open an existing
database first.} {Prima creare un nuovo archivio o aprirne uno
preesistente.}
{Current Master Password:} {Password principale corrente:}
{New Master Password:} {Nuova password principale:}
{Password Not Changed} {Password non modificata}
{You canceled the setting of a new password.
Therefore, the existing password remains in effect.} {L'impostazione della nuova password è stata annullata.
Di conseguenza, la password esistente rimane in effetto.}
{Master password changed.} {Password principale modificata.}
{Can not copy %s to clipboard: no %s defined.} {Impossibile copiare "%s" negli appunti: "%s" non è definito.}
{Copied %s to clipboard.} {Copiato %s negli appunti.}
{Password Gorilla} {Password Gorilla}
{Gorilla will protect your passwords and help you to manage them with a pwsafe 3.2 compatible database} {Gorilla protegge le vostre password o vi aiuta a gestire un archivio password compatibile con Pwsafe 3.2.}
Contributors Contributi
{Gorilla artwork contributed by %s} {Grafica del Gorilla a cura di %s}
{German translation by %s} {Traduzione in tedesco di %s}
{Russian translation by %s} {Traduzione in russo di %s}
{Italian translation by %s} {Traduzione in italiano di %s}
License Licenza
{About Password Gorilla} {Informazioni su Password Gorilla}
{Password Gorilla License} {Licenza di Password Gorilla}
{Find Text:} {Trova il testo:}
{Find Options ...} {Opzioni di ricerca}
{Any field} {Qualsiasi campo}
Title Titolo
Username {Nome utente}
Password Password
Notes Note
URL URL
{Case sensitive find} {Ricerca con confronto maiuscole/minuscole}
Find Trova
{Text not found.} {Testo non trovato.}
{Please select a login entry first.} {Selezionare prima una voce di login.}
{The selected login does not contain a URL value.} {Il login selezionato non contiene un valore URL.}
{Browser launching is not configured. See help.} {Il comando con cui eseguire il browser non è stato configurato. Controllare la guida.}
{Browser parameter lacks '%url%' string. See help.} {Il parametro del browser manca della stringa '%url%'. Controllare la guida.}
Error Errore
{Error launching browser, the OS error message is:} {Errore all'esecuzione del browser, il messaggio di errore è:}
{Oh well...} {Oh bene...}
{Launched browser:} {Avviato browser:}
{Generate gorilladoc.html} {Genera gorilladoc.html}
{Can not drag the selected items (see documentation)} {Impossibile trascinare gli elementi esistenti (consultare la documentazione)}
}
