# Project-Id-Version: Gorilla 1.5.3.5
# Report-Msgid-Bugs-To: 
# POT-Creation-Date: 2011-05-22 12:19+0200
# PO-Revision-Date: 2011-05-23 20:48+0800
# Last-Translator: Evgenii Terechkov <evg@altlinux.org>
# Language-Team: Russian <ru@li.org>
# MIME-Version: 1.0
# Content-Type: text/plain; charset=UTF-8
# Content-Transfer-Encoding: 8bit

mcmset ru {
File Файл
{New ...} {Новый ...}
{Open ...} {Открыть ...}
{Merge ...} {Объединить ...}
Save Сохранить
{Save As ...} {Сохранить как ...}
{Export ...} {Экспорт ...}
{Import ...} {Импорт ...}
{Preferences ...} {Предпочтения ...}
Exit Выход
Edit Правка
{Copy Username} {Копировать логин}
{Copy Password} {Копировать пароль}
{Copy URL} {Копировать URL}
{Clear Clipboard} {Очистить буфер обмена}
{Find ...} {Найти ...}
{Find next} {Найту далее}
Login Логин
{Add Login} {Добавить логин}
{Edit Login} {Редактировать логин}
{View Login} {Просмотреть логин}
{Delete Login} {Удалить логин}
{Move Login ...} {Перенести логин ...}
{Add Group ...} {Добавить группу ...}
{Add Subgroup ...} {Добавить подгруппу ...}
{Rename Group ...} {Переименовать группу ...}
{Move Group ...} {Перенести группу ...}
{Delete Group} {Удалить группу}
Security Безопасность
{Password Policy ...} {Политика паролей ...}
{Customize ...} {Настроить ...}
{Change Master Password ...} {Сменить мастер-пароль ...}
{Lock now} {Заблокировать сейчас}
Help Помощь
{Help ...} {Помощь ...}
{License ...} {Лицензия ...}
{About ...} {О программе ...}
{Need %s} {Нужен %s}
{The Password Gorilla requires the "%s" package. This seems to be an installation problem, as this file ought to be part of the Password Gorilla distribution.

Error message: %s} {Password Gorilla требует пакет "%s". Это похоже на проблему установки, так как этот файл входит в дистрибутив программы.

Сообщение об ошибке: %s}
{Need [Incr Tcl]} {Нужен [Incr Tcl]}
{The Password Gorilla requires the [incr Tcl] add-on to Tcl. Please install the [incr Tcl] package.

Error Message: %s} {Password Gorilla требует пакет [incr Tcl]. Пожалуйста, установите пакет [incr Tcl].

Сообщение об ошибке: %s}
{Need PWSafe} {Нужен PWSafe}
{The Password Gorilla requires the "pwsafe" package. This seems to be an installation problem, as the pwsafe package ought to be part of the Password Gorilla distribution.

Error Message: %s} {Password Gorilla требует пакет "pwsafe". Это похоже на проблему установки, так как pwsafe входит в дистрибутив программы.

Сообщение об ошибке: %s}
{Welcome to the Password Gorilla.} {Добро пожаловать в Password Gorilla}
About {О программе}
{Add Subgroup} {Добавить подгруппу}
{Rename Group} {Переименовать группу}
{Open URL} {Открыть URL}
{Copy Username to Clipboard} {Копировать логин в буфер обмена}
{Copy Password to Clipboard} {Копировать пароль в буфер обмена}
{Copy URL to Clipboard} {Копировать URL в буфер обмена}
{Move Login to:} {Переместить логин в:}
{Save changes?} {Сохранить изменения?}
{The current password database is modified. Do you want to save the current database before creating the new database?} {Текущая БД изменена. Хотите сохранить её до создания новой?}
{New Database: Choose Master Password} {Новая БД: выберите мастер-пароль}
{Password Gorilla - <New Database>} {Password Gorilla - <Новая БД>}
{<New Database>} {<Новая БД>}
{Add logins using <Add Login> in the <Login> menu.} {Добавьте логины используя <Добавить логин> в меню <Логин>.}
{Opening ... %2.0f %%} {Открытие ... %2.0f %%}
Database: БД:
Password: Пароль:
OK ОК
New Новая
{Select a database, and enter its password. Click "New" to create a new database.} {Выберите БД и введите её пароль. Нажмите "Новая" для создания новой БД.}
{Please be patient. Verifying password ...} {Будьте терпеливы. Проверка пароля ...}
{Error Opening Database} {Ошибка открытия БД}
{Can not open password database "%s": %s} {Невозможно открыть БД "%s": %s}
{Browse for a password database ...} {Выберите БД ...}
{Open Password Database} {Открыть БД паролей}
{Password database %s loaded.} {БД паролей %s загружена.}
{Add/Edit/View Login} {Добавить/Редактировать/Просмотреть логин}
Cancel Отмена
{Show Password} Показать
{Generate Password} Сгенерировать
{Override Password Policy} {Перекрыть политику}
{Password Length} {Длинна пароля}
{Hide Password} Скрыть
{Password policy settings invalid.} {Некорректные настройки политики паролей.}
<unknown> <неизвестно>
{This login must have a title, url or username.} {У логина должно быть название, ссылка или имя пользователя.}
{This login's group name is not valid.} {Имя группы некорректно.}
{New login added.} {Добавлен новый логин.}
{Login modified.} {Логин изменён.}
{Group entries may be renamed, not edited.} {Группы можно переименовывать, но не редактировать.}
{Destination Group with format <Group.Subgroup> :} {Группа назначения в формате <Группа.Подгруппа> :}
{Invalid Group Name} {Некорректное имя группы}
{The group name can not be empty.} {Имя группы не может быть пустым.}
{The name of the parent group is invalid.} {Имя родительской группы некорректно.}
{Are you sure that you want to delete this login?} {Уверены что хотите удалить этот логин?}
{Login deleted.} {Логин удалён.}
{Add a new Group} {Добавить группу}
Parent: Родитель:
{New Group Name:} {Новое имя группы:}
{Addition of group canceled.} {Добавление группы отменено.}
{New group added.} {Добавлена новая группа.}
{Root Node Can Not Be Moved} {Корень не может быть перенесён}
{The root node can not be moved.} {Корень не может быть перенесён.}
{Can Not Move Node} {Невозможно перенести узел}
{Can not move a group to a subgroup of itself.} {Невозможно перенести группу в её подгруппу.}
{Are you sure that you want to delete group and all its contents?} {Вы уверены что хотете удалить группу и всё её содержимое?}
{Group deleted.} {Группа удалена.}
{Group name unchanged.} {Имя группы изменено.}
{Group renamed.} {Группа переименована.}
{Export Security Warning} {Предупреждение безопасности при экспорте}
{You are about to export the password database to a plain-text file. The file will not be encrypted or password-protected. Anybody with access can read the file, and learn your user names and passwords. Make sure to store the file in a secure location. Do you want to continue?} {Вы собираетесь экспортировать БД в текстовый файл. Файл НЕ БУДЕТ зашифрован или защищён паролем. Любой сможет прочитать его и узнать ваши логины и пароли. Убедитесь, что сохраняете файл в надёжном месте. Продолжить?}
{Export password database as text ...} {Экспортировать БД как текст ...}
{Error Exporting Database} {Ошибка экспорта БД}
{Failed to export password database to} {Не удалось экспортировать БД в}
{Exporting ...} {Экспорт ...}
{Database exported.} {БД экспортирована.}
{Import CSV datafile} {Импорт из CSV}
{Error opening import CSV file} {Ошибка импорта из CSV}
{Could not access file } {Нет доступа к файлу }
{Error parsing CSV file} {Ошибка разбора CSV}
{Error parsing first line of CSV file, unable to continue.} {Ошибка разбора первой строки CSV-файла, невозможно продолжить.}
{Error, nothing to import.} {Ошибка, нечего импортировать.}
{No valid import data was found.  Please see
the help for details on how to format import
CSV data files for Password Gorilla.} {Не найдено подходящих данных.  Смотри справку о формате CSV-файла для Password Gorilla.}
{Error, undefined data columns} {Ошибка, неизвестные колонки}
{The following data items are not recognized as import data items.
Unable to continue.} {Следующие данные не распознанны как пригодные для импортирования.
Невозможно продолжить.}
{Some records from the CSV file were not imported.
Do you wish to save a log of skipped records?} {Некоторые записил из CSV-файла не были импортированы.
Хотите сохранить протокол этих записей?}
{Some records skipped during import} {Некоторые записи пропущены при импорте}
{Enter a file into which to save the log} {Укажите файл для сохранения протокола}
{record(s) successfully imported.} {запись(ей) импортированна(о) успешно.}
{Saving ... %2.0f %%} {Сохранение ... %2.0f %%}
{Merge Password Database} {Объединить БД}
Merging Объединение
Close Закрыть
{Warning: Can not save to} {Предупреждение: не могу сохранить в}
{because the file permissions are set for read-only access.} {т.к. есть права лишь на чтение файла.}
{Please change the file permissions to read-write and hit 'Retry' or hit 'Cancel' and use 'File'->'Save As' to save into a different file.} {Пожалуйста, смените права доступа на чтение-запись и нажмите 'Повтор' или нажмите 'Отмена' и сохраните БД в другой файл.}
{Warning: Read-only password file} {Предупреждение: БД в режиме только для чтения}
{Password database saved.} {БД сохранена.}
{Save password database ...} {Сохранить БД ...}
{Error Saving Database} {Ошибка сохранения БД}
{Failed to make backup copy of password database as "%s": %s} {Не удалось создать резервную копию БД как "%s": %s}
{Failed to save password database as "%s": %s} {Не удалось сохранить БД как "%s": %s}
{Password database saved as %s} {БД сохранена как %s}
{The current password database is modified. Do you want to save the database? <Yes> saves the database and exits. <No> discards all changes and exits. <Cancel> returns to the main menu.} {БД изменена. Хотите сохранить изменения?
"Yes" - сохранить БД и выйти, "No" - выйти без сохранения, "Cancel" - вернуться в программу.}
{Clipboard cleared.} {Буфер обмена очищен.}
{Database Locked} {БД заблокирована}
{Enter the Master Password.} {Введите мастер-пароль.}
{error: %s} {ошибка: %s}
{Wrong Password} {Неверный пароль}
{That password is not correct.} {Этот пароль некорректен.}
{Welcome back.} {Добро пожаловать назад.}
Confirm: Подтверждение:
{Passwords Do Not Match} {Пароли не совпадают.}
{The confirmed password does not match.} {Подтверждённый пароль не совпадает.}
{Password policy changed.} {Политика паролей изменена.}
{Use lowercase letters} {Использовать нижний регистр}
{Use UPPERCASE letters} {Использовать ВЕРХНИЙ регистр}
{Use digits} {Использовать цифры}
{Use hexadecimal digits} {Использовать шестнадцатиричные цифры}
{Use symbols (%, $, @, #, etc.)} {Использовать символы (%, $, @, #, ...)}
{Use easy to read characters only (e.g. no "0" or "O")} {Использовать лёгкие для чтения символы (без "0" и "O" и тп.)}
{Database Preferences} {Настройки БД}
{Lock when idle after} {Блокировка при бездействии}
{minutes (0=never)} {минут (0=никогда)}
{Auto-save database immediately when changed} {Авто-сохранение БД сразу после изменения}
{Use Password Safe 3 format} {Использовать формат Password Safe 3}
{V2 Unicode support} {Поддержка Unicode в V2}
{V3 key stretching iterations} {Количество итераций для V3}
Preferences Предпочтения
General Общие
{When double clicking a login ...} {При двойном щелчке по логину ...}
{Copy password to clipboard} {Копировать пароль}
{Launch Browser directed to URL} {Запустить браузер для URL}
{Do nothing} {Ничего не делать}
{Clear clipboard after} {Очищать буфер обмена после}
{seconds (0=never)} {секунд (0=никогда)}
Remember Запомнить
{database names} {последних БД}
Clear Очистить
{Backup database on save} {Создать резервную копию БД при сохранении}
{Remember sizes of dialog boxes} {Запоминать размеры окон}
{Use Gorilla auto-copy} {Использовать автоматическое копирование}
{Automatically copy password associated
with login to clipboard after pasting
of user-name.} {Автоматически копировать в буфер обмена
соответствующий пароль после вставки
логина.}
{This option does not function on
Windows(TM) or MacOS(TM) platforms.
See the help system for details.} {Эта опция не работает на
Windoes(tm) и MacOS(tm).
Подробности в документации.}
Defaults Умолчания
{Note: these defaults will be applied to new databases. To change a setting for an existing database, go to "Customize" in the "Security" menu.} {Эти настройки будут применены к новым БД. Для изменения настроек текущей БД, выберите пункт "Настройки БД" в меню "Безопасность"}
Export Экспорт
{Include password field} {Включать пароль}
{Include "Notes" field} {Включать заметки}
{Field separator} Разделитель
{Show security warning} {Показывать предупреждение безопасности}
Display Отображение
Language: Язык:
Size Размер
{Show Gorilla Icon} {Показывать изображение гориллы}
{Iconify upon auto-lock} {Сворачивать окно после блокировки}
{Hide login name in tree view} {Скрыть логин в дереве записей}
{This option takes effect after exiting
and restarting of Password Gorilla} {Эта опция начинает действовать после перезапуска программы}
Browser Браузер
{Browser executable to launch (required):} {Путь к браузеру (обязательно)}
{Command line parameter (if any) to pass (optional):} {Аргумент(ы) (необязательно)}
{Find Browser} {Найти браузер}
{If a command line parameter is provided, it must contain the character sequence: %url%. This sequence will be replaced with the actual URL during launch. See the help system for details.} {Если указана командная строка, она должна содержать последовательность %url%. Последняя будет заменена на реальную ссылку во время запуска. Подробности в документации.}
{Also copy username to clipboard} {Скопировать имя пользователя в буфер обмена}
{When selected the username
from the login entry will also
be copied to the clipboard
when opening a browser.} {Скопировать в буфер обмена логин при открытии браузера.}
{Determines how Password
Gorilla handles clearing the
clipboard.

Range zero to twenty.

See Help for details.} {Определяет как Password Gorilla очищает буфер обмена.

Значения от нуля до двенадцати.

Подробности в документации.}
{Clipboard autoclear multiplier} {Множитель автоматической очистки буфера обмена}
{History deleted. After a restart the list will be empty.} {История стёрта.}
{No Database} {Нет БД}
{Please create a new database, or open an existing
database first.} {Создайте новую БД или откройте существующую.}
{Current Master Password:} {Текущий мастер-пароль:}
{New Master Password:} {Новый мастер-пароль:}
{Password Not Changed} {Пароль не изменён}
{You canceled the setting of a new password.
Therefore, the existing password remains in effect.} {Вы отменили ввод нового пароля.
Действует существующий пароль.}
{Master password changed.} {Мастер-пароль сменён.}
{Can not copy %s to clipboard: no %s defined.} {Не могу скопировать %s в буфер обмена: %s не определён.}
{Copied %s to clipboard.} {%s скопирован в буфер обмена.}
{Password Gorilla} {О Password Gorilla}
{Gorilla will protect your passwords and help you to manage them with a pwsafe 3.2 compatible database} {Горилла защитит ваши пароли и поможет хранить их в БД, совместимой с pwsafe 3.2}
Contributors Контрибьюторы
{Gorilla artwork contributed by %s} {Рисунок гориллы сделан %s}
{German translation by %s} {Немецкий перевод сделан %s}
{Russian translation by %s} {Русский перевод сделан %s}
{Italian translation by %s} {Итальянский перевод сделан %s}
License Лицензия
{About Password Gorilla} {О Password Gorilla}
{Password Gorilla License} {Лицензия на Password Gorilla}
{Find Text:} Найти:
{Find Options ...} {Опции поиска ...}
{Any field} {Любое поле}
Title Заголовок
Username Логин
Password Пароль
Notes Заметки
URL URL
{Case sensitive find} {Учитывать регистр}
Find Найти
{Text not found.} {Текст не найден.}
{Please select a login entry first.} {Сначала нужно выбрать логин.}
{The selected login does not contain a URL value.} {У этого логина нет URL.}
{Browser launching is not configured. See help.} {Не указан способ запуска браузера. Подробности в документации.}
{Browser parameter lacks '%url%' string. See help.} {В аргументах браузеру отсутствует строка '%url'. Подробности в документации.}
Error Ошибка
{Error launching browser, the OS error message is:} {Ошибка запуска браузера:}
{Oh well...} Ох...
{Launched browser:} {Запущенный браузер:}
{Generate gorilladoc.html} {Создать gorilladoc.html}
{Can not drag the selected items (see documentation)} {Вы не можете перетащить выделенный элемент (см. документацию)}
}
