mcmset ru { \
"<New Database>" "<Новая БД>" \
"<unknown>" "<неизвестно>" \
"About" "О программе" \
"About ..." "О программе ..." \
"About Password Gorilla" "О Password Gorilla" \
"Add Group ..." "Добавить группу ..." \
"Add Login" "Добавить логин" \
"Add Subgroup" "Добавить подгруппу" \
"Add Subgroup ..." "Добавить подгруппу ..." \
"Add a new Group" "Добавить группу" \
"Add logins using <Add Login> in the <Login> menu." "Добавьте логины используя <Добавить логин> в меню <Логин>." \
"Add/Edit/View Login" "Добавить/Редактировать/Просмотреть логин" \
"Addition of group canceled." "Добавление группы отменено." \
"Also copy username to clipboard" "Скопировать имя пользователя в буфер обмена" \
"Any field" "Любое поле" \
"Are you sure that you want to delete group and all its contents?" "Вы уверены что хотете удалить группу и всё её содержимое?" \
"Are you sure that you want to delete this login?" "Уверены что хотите удалить этот логин?" \
"Auto-save database immediately when changed" "Авто-сохранение БД сразу после изменения" \
"Automatically copy password associated\nwith login to clipboard after pasting\nof user-name." "Automatically copy password associated\nwith login to clipboard after pasting\nof user-name." \
"Backup database on save" "Создать резервную копию БД при сохранении" \
"Browser" "Браузер" \
"Browser executable to launch (required):" "Путь к браузеру (обязательно)" \
"Browser launching is not configured. See help." "Browser launching is not configured. See help." \
"Browser parameter lacks '%url%' string. See help." "Browser parameter lacks '%url%' string. See help." \
"Can not copy $what to clipboard: no $what defined." "Не могу скопировать $what в буфер обмена: $what не определён." \
"Cancel" "Отмена" \
"Case sensitive find" "Учитывать регистр" \
"Change Master Password ..." "Сменить мастер-пароль ..." \
"Clear" "Очистить" \
"Clear Clipboard" "Очистить буфер обмена" \
"Clear clipboard after" "Очищать буфер обмена после" \
"Clipboard autoclear multiplier" "Clipboard autoclear multiplier" \
"Clipboard cleared." "Буфер обмена очищен." \
"Close" "Закрыть" \
"Command line parameter (if any) to pass (optional):" "Аргумент(ы) (необязательно)" \
"Confirm:" "Подтверждение:" \
"Contributors" "Контрибьюторы" \
"Copied $what to clipboard." "$what скопирован(но) в буфер обмена" \
"Copy Password" "Копировать пароль" \
"Copy Password to Clipboard" "Копировать пароль в буфер обмена" \
"Copy URL" "Копировать URL" \
"Copy URL to Clipboard" "Копировать URL в буфер обмена" \
"Copy Username" "Копировать логин" \
"Copy Username to Clipboard" "Копировать логин в буфер обмена" \
"Copy password to clipboard" "Копировать пароль" \
"Current Master Password:" "Текущий мастер-пароль:" \
"Customize ..." "Настроить ..." \
"Database Locked" "БД заблокирована" \
"Database Preferences" "Настройки БД" \
"Database exported." "БД экспортирована." \
"Database:" "БД:" \
"Defaults" "Умолчания" \
"Delete Group" "Удалить группу" \
"Delete Login" "Удалить логин" \
"Destination Group with format <Group.Subgroup> :" "Группа назначения в формате <Группа.Подгруппа> :" \
"Determines how Password\nGorilla handles clearing the\nclipboard.\n\nRange zero to twenty.\n\nSee Help for details." "Determines how Password\nGorilla handles clearing the\nclipboard.\n\nRange zero to twenty.\n\nSee Help for details." \
"Display" "Отображение" \
"Do nothing" "Ничего не делать" \
"Edit" "Правка" \
"Edit Login" "Редактировать логин" \
"Enter the Master Password." "Введите мастер-пароль." \
"Error" "Ошибка" \
"Error launching browser, the OS error message is:" "Ошибка запуска браузера:" \
"Exit" "Выход" \
"Export" "Экспорт" \
"Export ..." "Экспорт ..." \
"Export Security Warning" "Предупреждение безопасности при экспорте" \
"Export password database as text ..." "Экспортировать БД как текст ..." \
"Exporting ..." "Экспорт ..." \
"Field separator" "Разделитель" \
"File" "Файл" \
"Find" "Найти" \
"Find ..." "Найти ..." \
"Find Browser" "Найти браузер" \
"Find Options ..." "Опции поиска ..." \
"Find Text:" "Найти:" \
"Find next" "Следующее вхождение" \
"General" "Общие" \
"Generate Password" "Сгенерировать" \
"Generate gorilladoc.html" "Создать gorilladoc.html" \
"Group deleted." "Группа удалена." \
"Group name unchanged." "Имя группы изменено." \
"Group renamed." "Группа переименована." \
"Help" "Помощь" \
"Help ..." "Помощь ..." \
"Hide Password" "Скрыть" \
"History deleted. After a restart the list will be empty." "История стёрта." \
"Iconify upon auto-lock" "Сворачивать окно после блокировки" \
"If a command line parameter is provided, it must contain the character sequence: %url%. This sequence will be replaced with the actual URL during launch. See the help system for details." "If a command line parameter is provided, it must contain the character sequence: %url%. This sequence will be replaced with the actual URL during launch. See the help system for details." \
"Include \"Notes\" field" "Включать заметки" \
"Include password field" "Включать пароль" \
"Language:" "Язык:" \
"Launch Browser directed to URL" "Запустить браузер для URL" \
"Launched browser:" "Запущенный браузер:" \
"License" "Лицензия" \
"License ..." "Лицензия ..." \
"Lock now" "Заблокировать сейчас" \
"Lock when idle after" "Блокировка при бездействии" \
"Login" "Логин" \
"Login deleted." "Логин удалён." \
"Login modified." "Логин изменён." \
"Master password changed." "Мастер-пароль сменён." \
"Merge ..." "Объединить ..." \
"Merge Password Database" "Объединить БД" \
"Merging" "Объединение" \
"Move $type" "Переместить $type" \
"Move Group ..." "Перенести группу ..." \
"Move Login ..." "Перенести логин ..." \
"Moving of $type canceled." "Перемещение $type отменено." \
"New" "Новая" \
"New ..." "Новый ..." \
"New Database: Choose Master Password" "Новая БД: выберите мастер-пароль" \
"New Group Name:" "Новое имя группы:" \
"New Master Password:" "Новый мастер-пароль:" \
"New group added." "Добавлена новая группа." \
"New login added." "Добавлен новый логин." \
"Note: these defaults will be applied to new databases. To change a setting for an existing database, go to \"Customize\" in the \"Security\" menu." "Эти настройки будут применены к новым БД. Для изменения настроек текущей БД, выберите пункт \"Настройки БД\" в меню \"Безопасность\"" \
"Notes" "Заметки" \
"Notes:" "Заметки:" \
"Oh well..." "Ох..." \
"Open ..." "Открыть ..." \
"Open Password Database" "Открыть БД паролей" \
"Open URL" "Открыть URL" \
"Override Password Policy" "Перекрыть политику" \
"Parent:" "Родитель:" \
"Password" "Пароль" \
"Password Gorilla - <New Database>" "Password Gorilla - <Новая БД>" \
"Password Gorilla License" "Лицензия на Password Gorilla" \
"Password Length" "Длинна пароля" \
"Password Policy ..." "Политика паролей ..." \
"Password database %s loaded." "БД паролей %s загружена." \
"Password database saved as $nativeName" "БД сохранена как $nativeName" \
"Password database saved." "БД сохранена." \
"Password policy changed." "Политика паролей изменена." \
"Password policy settings invalid." "Некорректные настройки политики паролей." \
"Password:" "Пароль:" \
"Passwords Do Not Match" "Пароли не совпадают." \
"Please be patient. Verifying password ..." "Будьте терпеливы. Проверка пароля ..." \
"Please change the file permissions to read-write and hit 'Retry' or hit 'Cancel' and use 'File'->'Save As' to save into a different file." "Пожалуйста, смените права доступа на чтение-запись и нажмите 'Повтор' или нажмите 'Отмена' и сохраните БД в другой файл." \
"Preferences" "Предпочтения" \
"Preferences ..." "Предпочтения ..." \
"Remember" "Запомнить" \
"Remember sizes of dialog boxes" "Запоминать размеры окон" \
"Rename Group" "Переименовать группу" \
"Rename Group ..." "Переименовать группу ..." \
"Save As ..." "Сохранить как ..." \
"Save as Unicode text file" "Сохранить как текстовый файл Unicode" \
"Save changes?" "Сохранить изменения?" \
"Security" "Безопасность" \
"Select a database, and enter its password. Click \"New\" to create a new database." "Выберите БД и введите её пароль. Нажмите \"Новая\" для создания новой БД." \
"Show Gorilla Icon" "Показывать изображение гориллы" \
"Show Password" "Показать" \
"Show security warning" "Показывать предупреждение безопасности" \
"Size" "Размер" \
"Text not found." "Текст не найден." \
"The confirmed password does not match." "Подтверждённый пароль не совпадает." \
"The current password database is modified. Do you want to save the current database before creating the new database?" "The current password database is modified. Do you want to save the current database before creating the new database?" \
"The current password database is modified. Do you want to save the database? <Yes> saves the database and exits. <No> discards all changes and exits. <Cancel> returns to the main menu." "БД изменена. Хотите сохранить изменения?\n\"Yes\" - сохранить БД и выйти, \"No\" - выйти без сохранения, \"Cancel\" - вернуться в программу." \
"The selected login does not contain a URL value." "У этого логина нет URL." \
"This login must have a title." "У логина должно быть название." \
"This login's group name is not valid." "Имя группы некорректно." \
"This option does not function on\nWindows(TM) or MacOS(TM) platforms.\nSee the help system for details." "This option does not function on\nWindows(TM) or MacOS(TM) platforms.\nSee the help system for details." \
"Title" "Заголовок" \
"Use Gorilla auto-copy" "Использовать автоматическое копирование" \
"Use Password Safe 3 format" "Использовать формат Password Safe 3" \
"Use UPPERCASE letters" "Использовать ВЕРХНИЙ регистр" \
"Use digits" "Использовать цифры" \
"Use easy to read characters only (e.g. no \"0\" or \"O\")" "Использовать лёгкие для чтения символы (без \"0\" и \"O\" и тп.)" \
"Use hexadecimal digits" "Использовать шестнадцатиричные цифры" \
"Use lowercase letters" "Использовать нижний регистр" \
"Use symbols (%, \$, @, #, etc.)" "Использовать символы (%, \$, @, #, ...)" \
"Username" "Логин" \
"Using Password Gorilla" "Использование Password Gorilla" \
"V2 Unicode support" "Поддержка Unicode в V2" \
"V3 key stretching iterations" "Количество итераций для V3" \
"View Login" "Просмотреть логин" \
"Warning: Can not save to" "Предупреждение: не могу сохранить в" \
"Warning: Read-only password file" "Предупреждение: БД в режиме только для чтения" \
"Welcome back." "Добро пожаловать назад." \
"Welcome to the Password Gorilla." "Добро пожаловать в Password Gorilla" \
"When double clicking a login ..." "При двойном щелчке по логину ..." \
"When selected the username\nfrom the login entry will also\nbe copied to the clipboard\nwhen opening a browser." "When selected the username\nfrom the login entry will also\nbe copied to the clipboard\nwhen opening a browser." \
"You are about to export the password database to a plain-text file. The file will not be encrypted or password-protected. Anybody with access can read the file, and learn your user names and passwords. Make sure to store the file in a secure location. Do you want to continue?" "You are about to export the password database to a plain-text file. The file will not be encrypted or password-protected. Anybody with access can read the file, and learn your	user names and passwords. Make sure to store the file in a secure location. Do you want to continue?" \
"because the file permissions are set for read-only access." "т.к. есть права лишь на чтение файла." \
"database names" "последних БД" \
"minutes (0=never)" "минут (0=никогда)" \
"seconds (0=never)" "секунд (0=никогда)" \
"Hide login name in tree view" "Hide login name in tree view"
"This option takes effect after exiting\nand restarting of Password Gorilla" "This option takes effect after exiting\nand restarting of Password Gorilla"
"Please select a login entry first." "Please select a login entry first."
"Group entries may be renamed, not edited." "Group entries may be renamed, not edited."

"Gorilla artwork contributed by %s" "Gorilla artwork contributed by %s"
"German translation by %s"          "German translation by %s"
"Russian translation by %s"         "Russian translation by %s"
"Italian translation by %s"         "Italian translation by %s"
}
