mcmset ru {
	"File" "Файл" \
	"New ..." "Новый ..."\
	"Open ..." "Открыть ..." \
	"Merge ..." "Объединить ..."\
	"Save" "Сохранить"\
	"Add" "Добавить" \
	"Save As ..." "Сохранить как ..." \
	"Export ..." "Экспорт ..." \
	"Preferences ..." "Предпочтения ..." \
	"Preferences" "Предпочтения" \
	"Edit" "Правка" \
	"Copy Username" "Копировать логин" \
	"Copy Password" "Копировать пароль" \
	"Copy URL" "Копировать URL" \
	"Clear Clipboard" "Очистить буфер обмена" \
	"Find ..." "Найти ..." \
	"Find next" "Следующее вхождение" \
	"Manage" "Управление" \
	"Security" "Безопасность" \
	"Help ..." "Помощь ..." \
	"Help" "Помощь" \
	"License ..." "Лицензия ..." \
	"License" "Лицензия" \
	"Contributors" "Контрибьюторы" \
	"About ..." "О программе ..." \
	"Open Password Database" "Открыть БД паролей" \
	"Select a database, and enter its password." "Выберите БД и введите пароль" \
	"Create new password database" "Создать новую БД" \
	"Open password database" "Открыть БД паролей" \
	"Merge a second database into this database" "Объединить с другой БД" \
	"Add a new Group" "Добавить группу" \
	"Add Subgroup ..." "Добавить подгруппу ..." \
	"Add Group ..." "Добавить группу ..." \
	"Delete Group" "Удалить группу" \
	"Rename Group ..." "Переименовать группу ..." \
	"Parent Group" "Родительская группа" \
	"Group Name" "Группа" \
	"Notes:" "Заметки:" \
	"Show Password" "Показать" \
	"Hide Password" "Скрыть" \
	"Password Policy ..." "Политика паролей ..." \
	"Database Preferences" "Настройки БД" \
	"Database Preferences ..." "Настройки БД ..." \
	"Generate Password" "Сгенерировать" \
	"Change Master Password ..." "Сменить мастер-пароль ..." \
	"Override Password Policy" "Перекрыть политику" \
	"Password Length" "Длинна пароля" \
	"Use lowercase letters" "Использовать нижний регистр" \
	"Use UPPERCASE letters" "Использовать ВЕРХНИЙ регистр" \
	"Use digits" "Использовать цифры" \
	"Use hexadecimal digits" "Использовать шестнадцатиричные цифры" \
	"Use symbols (%, \$, @, #, etc.)" "Использовать символы (%, \$, @, #, ...)" \
	"Use easy to read characters only (e.g. no \"0\" or \"O\")" "Использовать лёгкие для чтения символы (без \"0\" и \"O\" и тп.)" \
	"Lock when idle after" "Блокировка при бездействии" \
	"minutes (0=never)" "минут (0=никогда)" \
	"Auto-save database immediately when changed" "Авто-сохранение БД сразу после изменения" \
	"Use Password Safe 3 format" "Использовать формат Password Safe 3" \
	"V2 Unicode support" "Поддержка Unicode в V2" \
	"V3 key stretching iterations" "Количество итераций для V3" \
	"General" "Общие" \
	"Clear clipboard after" "Очищать буфер обмена после" \
	"seconds (0=never)" "секунд (0=никогда)" \
	"Remember" "Запомнить" \
	"database names" "последних БД" \
	"Clear" "Очистить" \
	"When double clicking a login ..." "При двойном щелчке по логину ..." \
	"Copy password to clipboard" "Копировать пароль" \
	"(Not available with v2 database format.)" "(Недоступно в БД формата V2)" \
	"Add Login ..." "Добавить логин ..." \
	"Language" "Язык" \
	"Cancel" "Отмена" \
	"Edit Login ..." "Редактировать логин ..." \
	"Edit Login" "Редактировать логин" \
	"Delete Login" "Удалить логин" \
	"Do nothing" "Ничего не делать" \
	"Backup database on save" "Создать резервную копию БД при сохранении" \
	"Remember sizes of dialog boxes" "Запоминать размеры окон" \
	"Defaults" "Умолчания" \
	"Note: these defaults will be applied to\
		new databases. To change a setting for an existing\
		database, go to \"Database Preferences\" in the \"Manage\"\
		menu." "Эти настройки будут применены к новым БД. Для изменения настроек текущей БД, выберите пункт \"Настройки БД\" в меню \"Безопасность\"." \
	"Include password field" "Включать пароль" \
	"Include \"Notes\" field" "Включать заметки" \
	"Save as Unicode text file" "Сохранить как текстовый файл Unicode" \
	"Field separator" "Разделитель" \
	"Show security warning" "Показывать предупреждение безопасности" \
	"Close" "Закрыть" \
	"<New Database>" "<Новая БД>" \
	"Database:" "БД:" \
	"Browse" "Просмотр" \
	"Password:" "Пароль:" \
	"Please be patient. Verifying password ..." "Будьте терпеливы. Проверка пароля ..." \
	"Exit" "Выход" \
	"The Database Is Locked" "БД заблокирована" \
	"Enter the Master Password." "Введите мастер-пароль." \
	"Find" "Найти" \
	"Any field" "Любом поле" \
	"Title" "Заголовок" \
	"Username" "Логин" \
	"Case sensitive find" "Учитывать регистр" \
	"Welcome to the Password Gorilla." "Добро пожаловать в Password Gorilla" \
	"Add/Edit/View Login" "Добавить/Редактировать/Просмотреть логин" \
	"Password database saved as $nativeName" "БД сохранена как $nativeName" \
	"Password database saved." "БД сохранена." \
	"Current Master Password:" "Текущий мастер-пароль:" \
	"New Master Password:" "Новый мастер-пароль:" \
	"Confirm:" "Подтверждение:" \
	"The current password database is modified.\
		Do you want to save the database?\n\
		\"Yes\" saves the database, and exits.\n\
		\"No\" discards all changes, and exits.\n\
		\"Cancel\" returns to the main menu." "БД изменена. Хотите сохранить изменения?\n\"Yes\" - сохранить БД и выйти, \"No\" - выйти без сохранения, \"Cancel\" - вернуться в программу." \
	"Login unchanged." "Логин не изменён" \
	"Copy Username to Clipboard" "Копировать логин в буфер обмена" \
	"Copy Password to Clipboard" "Копировать пароль в буфер обмена" \
	"Copy URL to Clipboard" "Копировать URL в буфер обмена" \
	"Add Login" "Добавить логин" \
	"Add Subgroup" "Добавить подгруппу" \
	"Rename Group" "Переименовать группу" \
	"Copied password to clipboard." "Пароль скопирован в буфер обмена." \
	"Using Password Gorilla" "Использование Password Gorilla" \
	"Database exported." "БД экспортирована." \
	"Exporting ..." "Экспорт ..." \
	"Export password database as text ..." "Экспортировать БД как текст ..." \
	"Export Security Warning" "Предупреждение безопасности при экспорте" \
	"You are about to export the password\
			database to a plain-text file. The file will\
			not be encrypted or password-protected. Anybody\
			with access can read the file, and learn your\
			user names and passwords. Make sure to store the\
			file in a secure location. Do you want to\
			continue?" "Вы собираетесь экспортировать БД паролей в текстовый файл. Он НЕ БУДЕТ зашифрован\
                        или защищён паролем. Каждый имеющий допуск сможет прочитать его и узнать ваши логины/пароли. \
                        Убедитесь, что сохраняете файл в надежном месте. Хотите продолжить?" \
	"Copied user name to clipboard." "Логин скопирован." \
	"Copied URL to clipboard." "URL скопирован." \
	"Can not copy URL to clipboard: no URL defined." "Не могу скопировать URL: URL не определён." \
	"Clipboard cleared." "Буфер обмена очищен." \
	"Any field" "Любое поле" \
	"Find Options ..." "Опции поиска ..." \
	"Login deleted." "Логин удалён." \
	"Are you sure that you want to delete this login?" "Уверены что хотите удалить этот логин?" \
	"Move Login ..." "Перенести логин ..." \
	"Move Group ..." "Перенести группу ..." \
	"Move" "Перенести ..." \
	"Group" "Группа" \
	"Destination Group with format <Group.Subgroup> :" "Группа назначения в формате <Группа.Подгруппа> :" \
	"Database Locked" "БД заблокирована" \
	"Merge Password Database" "Объединить БД" \
	"Add logins using <Add Login> in the \"Login\" menu." "Добавьте логины используя <Добавить логин> в меню \"Логин\"." \
	"Password database $nativeName loaded." "БД паролей $nativeName загружена." \
	"Addition of new login canceled." "Добавление логина прервано." \
	"New login added." "Добавлен новый логин." \
	"Login modified." "Логин изменён." \
	"Group deleted." "Группа удалена." \
	"Group name unchanged." "Имя группы изменено." \
	"Group renamed." "Группа переименована." \
	"Merging " "Объединение " \
	"Welcome back." "Добро пожаловать назад." \
	"Password policy changed." "Политика паролей изменена." \
	"Text not found." "Текст не найден." \
	"Parent:" "Родитель:" \
	"Are you sure that you want to delete group and all its contents?" "Вы уверены что хотете удалить группу и всё её содержимое?" \
	"New Group Name:" "Новое имя группы:" \
	"Find Text:" "Найти:" \
	"New" "Новая" \
	"Select a database, and enter its password. Click \"New\" to create a new database." "Выберите БД и введите её пароль. Нажмите \"Новая\" для создания новой БД." \
	"New Database: Choose Master Password" "Новая БД: выберите мастер-пароль" \
        "Customize ..." "Настроить ..." \
        "Login" "Логин" \
        "Export" "Экспорт" \
        "Display" "Отображение" \
        "Language:" "Язык:" \
        "Size:" "Размер:" \
        "Notes" "Заметки" \
        "Password" "Пароль" \
        "Group:" "Группа:" \
        "Title:" "Заголовок:" \
        "Username:" "Логин:" \
        "Last Password Change:" "Смена пароля:" \
        "Last Modified:" "Изменение:" \
        "Lock Now" "Заблокировать сейчас" \
        "View Login" "Просмотреть логин" \
	}
	
mcunknown de "unbekannt"
