.TH "PASSWORD-GORILLA" "1" 
.SH "NAME" 
password-gorilla \(em a password manager 
.SH "SYNOPSIS" 
.PP 
\fBpassword-gorilla\fR 
.SH "DESCRIPTION" 
.PP 
The Password Gorilla helps you manage your logins. It stores all your 
user names and passwords, along with login information and other 
notes, in a securely encrypted file. A single "master password" is 
used to protect the file. This way, you only need to remember the 
single master password, instead of the many logins that you use. 
 
.PP 
If you want to log in to a service or Web site, the Password Gorilla 
copies your user name and password to the clipboard, so that you can 
easily paste it into your Web browser or other application. Because 
the password does not appear on the screen, Password Gorilla is safe 
to use in the presence of others. 
 
.PP 
The convenience of Password Gorilla allows you to choose different, 
non-intuitive passwords for each service. An integrated random 
password generator can provide one-time passwords, tunable to various 
services' policies. 
 
.SH "FILES" 
.PP 
The program creates a configuration file \fB.gorillarc\fP in the homedirectory of the user. 
 
.SH "REPORTING BUGS" 
.PP 
Bugs can be reported through the Debian Bug Tracking System at http://bugs.debian.org. 
 
.SH "AUTHOR" 
.PP 
Author of password-gorilla is Frank Pilhofer <fp@fpx.de>
.PP
Current maintainers are Zbigniew Diaczyszyn <> and Richard Ellis <>.
.PP 
This manual page was written by Patrick Schoenfeld <schoenfeld@in-medias-res.com> for 
the \fBDebian\fP system (but may be used by others).  Permission is 
granted to copy, distribute and/or modify this document under 
the terms of the GNU General Public License, Version 2 any 
later version published by the Free Software Foundation. 
 
.PP 
On Debian systems, the complete text of the GNU General Public 
License can be found in /usr/share/common-licenses/GPL. 
 
.\" created by instant / docbook-to-man, Wed 18 Nov 2009, 00:36 
